### ISSUE TITLE
Indicate when there's a pending alias/implication/BUR attached to a topic

### ISSUE THREAD

**Issue by Type-kun** [danbooru/danbooru#2751]
When there's a backlog of aliases/implications and they get processed en masse, some are immediately approved/rejected while for some further discussion is required and prompted by admin. The problem is, there's no easy way to tell: there's a whole bunch of topics last updated by admin, and that's it. 

Theoretically speaking, it should be possible to do a query to find if there are pending aliases/implications/BURs attached to the topic and somehow indicate that in the forum listing. naive approach to that would result in 120 additional queries for 40-topic listing, though, so I'm not sure whether that's worth it. Maybe some other kind of indication can be used, like adding `[Resolved]` to topic name once the last attached request is processed, but that doesn't seems reliable at all.

**Comment by crs00** [comment]
Couldn't you just have DanbooruBot add [PENDING] to the beginning of a thread title where the OP is a pending alias/implication/BUR/whatnot, similar to how it adds [REJECTED] or [APPROVED] to the beginning of the same type of threads depending on the outcome of the OP's request?

**Comment by BrokenEagle** [comment]
The current system of indicating an approved/rejected/failed BUR is somewhat flawed in that it breaks down when more than one BUR is attached to the same topic. Instead of modifying the topic title, wouldn't it be better to include all of the BURs for the shown topics and have some kind of counter displayed around the topic title indicating how many approved/rejected/failed/pending BURs are currently attached to the topic? Something like the following.

![image](https://user-images.githubusercontent.com/21149935/74595842-841b7900-4ffb-11ea-9fc4-fda82403b60f.png)

- **Source code:** https://github.com/BrokenEagle/danbooru/tree/forum-topic-bur-status-indicators

Since BURs can be included in the index action, it only requires a single SQL query per page load. Additionally, since the BUR table is so small, and the average amount of BURs per topic is small, then including them all for doing the counts like that should impose too much of an additional load.

If the above is fine, then I can go ahead and polish up that branch and submit it as a PR.

**Comment by evazion** [comment]
This is fine. The problem in the past was that we had three separate types of requests to deal with: alias requests, implication requests, and bulk update requests. Now that we just have to deal with BURs this is easier.
