### ISSUE TITLE
Ability to "report" forum posts, comment threads and users

### ISSUE THREAD

**Issue by Type-kun** [danbooru/danbooru#2837]
When something goes haywire in comment threads or forums and mod attention is needed, users currently have two choices - either create/find a forum topic to mention that something goes wrong, or dmail a few mods. First method is good for mod staff, but can make user a target for retaliation as a whistleblower, and second method causes quite a lot of annoyance from people who are dmailed if that happens more than a few times, not to mention they might not actually see it until much later.

What I propose is a way for users to "flag" or "report" inappropriate comment thread, forum post, forum thread, or user, which will simultaneously notify all of the mod staff without revealing the reporter to offenders. It should offer a possibility for user to leave a comment describing what's wrong.

I initially thought about a separate table and page where such reports would be recorded. An unresolved record would create a notice similar to "check the queue" for mod+ staff. The first mod to deal with the report would mark it as "resolved", so that others are not bothered with it if they login later. A report should also have an option to "hide" similar to queue if the mod can't solve it and don't want to be bothered. Visiting the report page should remove the notice for a certain period, unless new reports are added.

However, after thinking about it more, there's a much simpler method: create a mod+ topic, maybe make it sticky, record its ID in the config, and have "report" button create a forum post from reporting user in that topic. This way, every moderator who visits the forums would see it and react if necessary. On a plus side, it's much, much simpler to code, uses the existing facilities, and automatically gives mods means of discussing the reports. On the negative side, mods still should visit the forum to see it, and resolved case would still alert everyone.

**Comment by r888888888** [comment]
I like that idea.

One thing that needs to be ironed out is what are good reasons for flagging a comment or forum post. Verbal abuse is an obvious one (although even that needs to be objectively measured in some way).

**Comment by kdoshere** [comment]
In my opinion I like the first idea, it needs to be separated from the forum and it doesn't matter if the forum threads are hidden or not, sooner or later they are forgotten or distorted.

Because of that I'd prefer a site were we can have a centralized management for this matters, like a ticket system from a customer service support center.
And then when an user creates a ticket he can leave the reason for the ticket and the moderators can take care of that, discuss if needed by using simple comments and then when everything is done then the ticket can be marked as solved or reviewed.

In the case of the comments and how to measure them, maybe we could use an option like "when this comment has a negative score of -10 or more" = the option to report it will appear.

This could work hmmm
