### ISSUE TITLE
Uploading from Tumblr should select the original source and artist in case of reblogs

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#3619]
Example:
http://twrlare.tumblr.com/post/172838862051/

Danbooru selects twrlare as the artist in the upload page, but the actual source is https://pencilanon.tumblr.com/post/172837943488/.
There should be some mechanism that checks if the post is a reblog first, and extrapolates the right url/artist tag in that case.

**Comment by evazion** [comment]
Wontfix. The bug here was that when you uploaded a reblog, we included images from the original post in the upload, even though they belonged to a different post. This was wrong for reasons explained in https://github.com/danbooru/danbooru/commit/e28b403fba0ba8fdaf95a78c040c24d3ffdda25c. Instead you should just upload the original post directly.

This basically meant that if you tried to upload https://www.tumblr.com/shortgremlinman/707877745599905792/get-asked-idiot, it would grab every image in the thread, instead of just from the specific post you were uploading. This was wrong because each image was by a different person, but normally we assume all images in an upload belong to the same post by the same user.
