### ISSUE TITLE
Tag relationship retirer and implications

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4101]
I just realized that the "underused" test gets applied to the consequent for both aliases and implications.

https://github.com/danbooru/danbooru/blob/ea4e7f197001dc2d699ce702a129e8a3cbc6bc9e/app/logical/tag_relationship_retirement_service.rb#L47-L51

That makes sense for aliases, but I'm not sure if it makes sense for implications. An implication could be kept around if the consequent tag was popular enough, even if the antecedent tag hasn't been used for several years or more.

**Comment by nonamethanks** [comment]
I just noticed this a couple weeks ago, some implications have been retired, but I don't think it's a good idea that they are, because they're still valid. Implications serve a different purpose than aliases, so they shouldn't be retired.

See: 

https://danbooru.donmai.us/forum_topics/15484?page=5#forum_post_164885
https://danbooru.donmai.us/forum_topics/15484?page=5#forum_post_165820
https://danbooru.donmai.us/forum_topics/15484?page=5#forum_post_166638

**Comment by evazion** [comment]
This was fixed in a5f589f. Implications are now only retired if one of the tags is empty.
