### ISSUE TITLE
Non-contributors can bypass the upload limit

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4102]
It seems like [user #604269](https://danbooru.donmai.us/users/604269) was able to take advantage of a race condition to upload 3x their normal allotment of uploads (36 instead of 12).

![image](https://user-images.githubusercontent.com/21149935/61766225-ecbbb380-ad94-11e9-9d5c-48baffcc8d5a.png)

Looking at that user's batch of uploads, it seems like they uploaded 30 posts in 26 seconds.

https://danbooru.donmai.us/posts?tags=user%3Aqme+id%3A3575749..3575779

Perhaps non-contributors need to be restricted to uploading no more than one upload at a time, and then run a limit check each time they upload?

**Comment by evazion** [comment]
This happens when you open a bunch of uploads with the bookmarklet at the same time then submit them later. The upload limit check is performed when the upload is created, but this became wrong when preprocessed uploads were added. It means you can start an upload when you're below your upload limit, pass the check, then submit it later even after you've gone over your limit.

**Comment by evazion** [comment]
Fixed in 3c2a379d6.
