### ISSUE TITLE
The database timed out running your query

### ISSUE THREAD

**Issue by fjay69** [danbooru/danbooru#4197]
An error caused by this url: https://danbooru.donmai.us/posts?tags=transparent_background+white_background+&ms=1

    ActiveRecord::QueryCanceled exception raised
    app/logical/pagination_extension.rb:73:in `records'
    app/logical/post_sets/post.rb:138:in `posts'
    app/controllers/posts_controller.rb:14:in `index'

**Comment by BrokenEagle** [comment]
That's nothing. It's what happens when the query times out.

You're a [Member-level user](https://danbooru.donmai.us/users/427425), so you only get 3 seconds before this happens. You're also searching for 2 tags so you can't use the range specifier metatags `id:`, `age:`, or `date:`. You can however use the `limit:` metatag for free.  I tried it though and it only lets you see the first few. The problem is is that those posts are spread throughout the entire post database and there's not a whole lot there (only 28).

**Comment by fjay69** [comment]
I understand, but this error did not happen a year ago.

**Comment by nonamethanks** [comment]
A prettier error is now displayed when this happens, so this can be closed I think.
