### ISSUE TITLE
Have single result searches go to the show pages for certain controllers

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4204]
This would be to match the current behavior of the wiki pages controller, plus it would shorten what is currently a two step-process of search, then click the single result.

This should be done for:

1. Artists
    - Example: https://danbooru.donmai.us/artists?search%5Bany_name_matches%5D=maco_spl
2. Pools
    - Example: https://danbooru.donmai.us/pools/gallery?search%5Bname_matches%5D=Disgustingly_Adorable
3. Forum topics
    - Example: https://danbooru.donmai.us/forum_topics?search%5Btitle_ilike%5D=%5BBUR%5D+Girls+und+Panzer
4. Users
    - Example: https://danbooru.donmai.us/users?search%5Bname_matches%5D=albert

I'm not sure if this behavior on any of the other controllers would be useful.

Also, this could also be a potential search term addon for those that don't want that behavior, i.e. `search[display_single]=true` would bring up the show page for a single match whereas the false condition would not. I'm not sure which way should be the default though. However, to do that on the application controller would require overrides on all of the controllers without show pages, so it might be easier to this on the individual controllers instead if this actually gets implemented.

**Comment by evazion** [comment]
For now this only works when using the quick search box (or when passing the `redirect` param), and only when the result is an exact name match. An exact match is required because I think this only makes sense when you're trying to look up a wiki / artist / user by name. It shouldn't trigger when you do, for example, a wildcard search that just-so-happens to return a single result.

I'm not doing this for forum searches because I think it would be unexpected. It's not normally expected for forum searches to return a single result. If one does, it was most likely by accident. Requiring an exact title match doesn't quite work either. If you search for `Touhou` you probably didn't mean the topic literally named `Touhou` ([1](https://danbooru.donmai.us/forum_topics/760)).

**Comment by BrokenEagle** [comment]
This might be true for most uses, however my IndexedAutocomplete script does find singular matches on forum titles because it already does the searching through the autocomplete.
