### ISSUE TITLE
Incomplete IP address results

### ISSUE THREAD

**Issue by RaisingK** [danbooru/danbooru#4209]
user #596289's post changes show multiple addresses, but `/ip_addresses?search[group_by]=ip_addr&search[user_id]=596289` only returns the latest.  Searching for the oldest address yields no results.

**Comment by evazion** [comment]
`/ip_addresses` doesn't support IPs from post versions or pool versions yet. This is a known limitation. Post and pool versions live in a separate database, which means we can't join these tables with tables from the main database. Post and pool versions need to be migrated back to the main database for this to work.

In the meantime, https://danbooru.donmai.us/moderator/ip_addrs still works. (It works here because we're counting the IPs in each table separately, then combining the results together at the end. This works but it's slower and less flexible than what `/ip_addresses` is doing.)

**Comment by RaisingK** [comment]
What about also adding addresses from forum posts?

**Comment by evazion** [comment]
Unfortunately IPs have been never tracked for forum posts, and I think it's too late to start now.

**Comment by evazion** [comment]
Closing as obsolete. The https://danbooru.donmai.us/moderator/ip_addrs and https://danbooru.donmai.us/ip_addresses pages have been removed. IP addresses have been nuked from everywhere except the <https://danbooru.donmai.us/user_events> page. Now the only time IP addresses are tracked is when a user signs up, logs in, logs out, or performs some other account security related action (changes their password or email, etc). Tracking logins and signups is sufficient for detecting sockpuppets.
