### ISSUE TITLE
Incorrect field `tag_count`

### ISSUE THREAD

**Issue by gastrodon** [danbooru/danbooru#4245]
When looking at post [1](https://testbooru.donmai.us/posts/1.json) on `testbooru.donmai.us` the following fields contradict each other
```json
{
    "tag_string_meta":"lowres tagme",
    "tag_count_meta":0
}
```
The same mismatch occurs for `tag_*_copyright` and `tag_*_character`

This appears to be an issue that popped up and been fixed before

**Comment by nonamethanks** [comment]
Closing this since it was testbooru and it doesn't seem like it's an issue anymore.

**Comment by gastrodon** [comment]
If this is an issue that seems to come and leave, maybe some ticket should be tracking it?

**Comment by nonamethanks** [comment]
Since it was testbooru it's impossible to tell whether it's an issue that happens on the main site or if it was just the effect of database editing / shuffling in the test environment, since testbooru went through several iterations. Those counts are recalculated on every tag edit so they cant really be wrong unless something bad happened, or for very old posts that haven't been touched in a long time and were edited when a bug existed. 

If you find an incorrect count in the live site I'll reopen this and do a global scan to fix them however.
