### ISSUE TITLE
Why are there no children_ids in the Posts api?

### ISSUE THREAD

**Issue by Akise** [danbooru/danbooru#4299]
Has it been modified?

**Comment by lllusion3469** [comment]
It has indeed been modified in 8649ff6dbe313c36cdb02f3aa096528ccca18225:

> API: remove various associated fields included by default.
> 
> Remove various associated fields that were included by default on
> certain endpoints. API users can use the only param to include the
> full association if they need these fields.
> 
> * `/artists.json`: `urls`.
> * `/artist_urls.json`: `artist`.
> * `/comments.json`: `creator_name` and `updater_name`.
> * `/notes.json`: `creator_name`.
> * `/pools.json`: `creator_name`.
> * `/posts.json`: `uploader_name`, `children_ids`, `pixiv_ugoira_frame_data`.
> * `/post_appeals.json`: `is_resolved`.
> * `/post_versions.json`: `updater_name`.
> * `/uploads.json`: `uploader_name`.

My problem with this is that it isn't documented at all (at least in [help:api](https://danbooru.donmai.us/wiki_pages/help:api)).

One of my use cases that's affected is getting all artists of a specific post and their URLs. In `/posts/<id>.json` you only get the artist names so you have to use the `/artists.json?search[name]=<name>` parameter. If `/artist_urls.json` was documented I would probably conclude I would have to use that with the artist ids from `/artists.json` somehow but as it is now with both `?only` and `/artist_urls.json` undocumented it seems impossible just based on [help:api](https://danbooru.donmai.us/wiki_pages/help:api).

I only knew how to solve it (with `?only=urls,...`) because i have a feed of this repository's commits in my feed reader.

**Comment by BrokenEagle** [comment]
See [forum #163283](https://danbooru.donmai.us/forum_posts/163283) for how to get children IDs.

**Comment by evazion** [comment]
API changes are documented in [topic #9127](https://danbooru.donmai.us/forum_topics/9127).
