### ISSUE TITLE
Looking for tag [superset] difference for popular tags results in "something broke" page

### ISSUE THREAD

**Issue by iamtakingiteasy** [danbooru/danbooru#4337]
Example queries:

https://danbooru.donmai.us/posts?tags=-touhou+chen
https://danbooru.donmai.us/posts?tags=-fate_%28series%29+astolfo_%28fate%29

There is no such problem with smaller queries, e.g.

https://danbooru.donmai.us/posts?tags=-serial_experiments_lain+iwakura_lain

**Comment by BrokenEagle** [comment]
This is not an issue with Danbooru. It is because searching through millions of records with an extremely low probability of a hit plus requiring a large amount of records in a batch is very highly guaranteed to cause a database timeout, especially if your user level is low. You can either use range and/or the limit metatags to reduce the time needed to complete the query and thus avoid a database timeout. This might mean that several to dozens of queries might need to be run to search all of the posts. See [Help:Sheetsheet](https://danbooru.donmai.us/wiki_pages/help:cheatsheet) for more information about how to use those metatags.

If that's all and there's nothing more, then you can go ahead and close the issue. I'll close it after a day if there's no response.
