### ISSUE TITLE
Save commentary by default

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4377]
This was mentioned multiple times before, opening it so it's not forgotten.

Some commentaries aren't worth saving, but it's better that that decision is left to users afterwards rather than excluding it by default.
Most users don't bother checking the "include commentary" box either or are not aware of it, so a lot of them get inevitably lost if artists nuke their entire accounts or the source is deleted.
It's better to save the metadata by default.

**Comment by BrokenEagle** [comment]
Issue #4113 is a similar idea to this, but this is something that is more doable in the meantime.

However, there should be a few caveats:

1. Only auto-check the "Include commentary" checkbox

    I.e. don't force the users to include the commentary if they don't want to.

2. Only auto-check the "Include commentary" on the first picture for posts with more than one image

   Because the same commentary isn't needed on 100+ pictures. That's wasted information.

@nonamethanks brought up a good point on Discord though, in that a user may not visit the first image in a parent/child relationship, and so wouldn't necessarily see the commentary. Therefore, the children of a parent should show the commentary of the parent, if they are from the same source and if they don't already have commentary themselves.

An alternative to this would be to have a way to specify on a post where to pull its commentary from. So it would be something similar to the **parent_id** field on posts.

At the top of such included commentaries, it should put at the top of the commentary like "*Commentary from post # 1234*".

**Comment by nonamethanks** [comment]
I agree with not including commentary from large batches (no use for "twitter log"-style pixiv posts), but as a lot of posts come from twitter nowadays it's not uncommon for meaningful commentary to come in groups of 2 to 4 pictures. 

Only fetching the commentary for the first image and attaching it to the rest would offset this problem, but doesn't include cases where for example the first post is not uploaded. A better way for this problem would be to entirely detach the commentary from the concept of images as individual posts and bind it to the actual artist's "post", but that'll have to wait for the implementation of the anonymous pools that @evazion mentioned will replace the parent-child relationship in a distant future.
