### ISSUE TITLE
Bookmarklet not working on Tumblr sites using a non-standard URL format

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4380]
Brought up by Etour on Danbooru ([forum #164681](https://danbooru.donmai.us/forum_posts/164681)). Basically, Danbooru isn't detecting those kind of links as Tumblr links.

- Example URL: https://d-floe.com/post/190738927749/commission-of-kat-from-gravity-rush
- Source query: https://danbooru.donmai.us/source.json?url=https%3A%2F%2Fd-floe.com%2Fpost%2F190738927749%2Fcommission-of-kat-from-gravity-rush

<hr>

I check for these myself by parsing the URL path and checking for either an post-type path or an image-type path.

- Post path:
    - Regex: `\/post\/\d+(\/.|$)
    - Examples: `/post/12345` or `/post/12345/something`
- Image path:
    - Regex: `\/image\/\d+$`
    - Example: `/post/12345`

<hr>

Then I check that there isn't an extension at the end of the path.

- Regex:  `[^.]+\..+$`
- Example: `/image/1234.jpg`

Any positive matches get thrown out.

<hr>

Then I do a HEAD request to the URL. It fails if:

1. The HEAD request fails in any way or doesn't return a 200 status code
2. `content-type` is not in the header
3. `content-type` does not contain `text/html`
4. `X-Tumblr-User` or `Set-Cookie` are not in the header

If `X-Tumblr-User` is in the header, then it instantly passes. If not, then it checks `Set-Cookie` for any  cookie where `domain=.tumblr.com`

<hr>

All in all, I'm not sure how feasible all of the above is for the current **Sources** module. It would require a lot of code for such a small use case, and I'm not sure how much it would be worth doing. I'd like for others to chime in on this as well though before any work gets started, just so we can explore the best path forward with these.

**Comment by nonamethanks** [comment]
It's just a redirect, no need for all that.  
https://d-floe.tumblr.com/post/190738927749/commission-of-kat-from-gravity-rush grabs the correct one:

https://danbooru.donmai.us/source.json?url=https%3A%2F%2Fd-floe.tumblr.com%2Fpost%2F190738927749%2Fcommission-of-kat-from-gravity-rush
https://danbooru.donmai.us/uploads/batch?batch%5Burl%5D=https%3A%2F%2Fd-floe.tumblr.com%2Fpost%2F190738927749%2Fcommission-of-kat-from-gravity-rush&commit=Fetch

The full size is under "alt_sizes", which ties back to issue #4324, because we should go through all alt_sizes+original size images and compare their size, and pick the bigger one, rather than hardcode the bigger format. In this case for example the bigger pic is under the alt_sizes array but the original_size one is smaller.

**Comment by BrokenEagle** [comment]
There are many custom Tumblr domains where the username is not easily discernible.

- https://tightenupthe.graphics/ (username: artcrossaura)
- https://yra.sixc.me/ (username: yraa)
- https://monor.us/ (username: monorus)
- https://kana.moe/ (username: kanachiro)

Besides that, it's not really possible to tell what link is a Tumblr link and which one isn't just from the link alone. Having to do a HEAD request isn't optimal, but it's better than doing a full GET request. After of course validating that the link itself falls within the allowable format as I described above.
