### ISSUE TITLE
Invalid metasearches should return empty results, rather than all posts

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4389]
Examples:
[user:fakeuser123123](https://danbooru.donmai.us/posts?tags=user%3Afakeuser123123&ms=1)
[age:>notadate](https://danbooru.donmai.us/posts?tags=age%3A%3Enotadate&ms=1)
[rating:0/10](https://danbooru.donmai.us/posts?tags=rating%3A0%2F10&ms=1)

**Comment by lllusion3469** [comment]
This already happens for some cases like [`favgroup:foo`](https://github.com/danbooru/danbooru/blob/6d615001e4fcfdeb123f0f64cc47f3f30a044fed/app/logical/post_query_builder.rb#L846) where it causes errors (with less than ideal messages) like this:
> ### Error
> That record was not found.

but for e.g. `user` [it's explicitly ignored](https://github.com/danbooru/danbooru/blob/6d615001e4fcfdeb123f0f64cc47f3f30a044fed/app/logical/post_query_builder.rb#L711).

For `rating` there's just no `else` in [this `if`](https://github.com/danbooru/danbooru/blob/6d615001e4fcfdeb123f0f64cc47f3f30a044fed/app/logical/post_query_builder.rb#L446)

For `age` when it  tries to [`DurationParser.parse`](https://github.com/danbooru/danbooru/blob/6d615001e4fcfdeb123f0f64cc47f3f30a044fed/app/logical/duration_parser.rb#L2) the value it just produces `0 seconds` so
* for `age:>foo` it's everything uploaded before `now`, i.e. everything
* for `age:<foo` it's everything uploaded after `now`, i.e. nothing

**Comment by nonamethanks** [comment]
Rather than erroring out, the ideal behaviour would be to have it return empty results, to match searches for tags that don't exist, but yeah it'd be equivalent since in any case there'd be no results to display.

**Comment by nonamethanks** [comment]
Also I should add, "That record was not found" is not a very descriptive error. If it becomes the default it should be personalized for each tag (example, "That user was not found"), otherwise to the average user it's not very clear what it means.

**Comment by lllusion3469** [comment]
> Rather than erroring out, the ideal behaviour would be to have it return empty results, to match searches for tags that don't exist

For tags because of the way the search is implemented, (as far as I understand it) there is no way to error out if a tag doesn't exist without slowing down the search unnecessarily by manually checking (don't know whether that's worth it). For the purpose of the search every tag exists, but some don't have matching posts. It never actually checks whether that tag appears in the `tag` table because it doesn't need to.

Even e.g. [`artist:haruyama_kazunori` gives no result](https://danbooru.donmai.us/posts?tags=artist%3Aharuyama_kazunori&ms=1) even though there's [~4089 posts](https://danbooru.donmai.us/tags?commit=Search&search%5Bcategory%5D=1&search%5Bhide_empty%5D=yes&search%5Border%5D=count) because of the way tag search is handled.

For most other cases erroring out would arguably be the more natural behaviour. 

> Also I should add, "That record was not found" is not a very descriptive error.

Well, I also called it "less than ideal". Currently it's just the message ActiveRecord generates.  Was possibly not even intended.
