### ISSUE TITLE
custom_css.rb: wrong regexp for adding !important

### ISSUE THREAD

**Issue by fjay69** [danbooru/danbooru#4398]
#1871
It seems that RegExp does a replacement: ; -> !important;
But in this case
`{background-image: url(data:image/png;base64,base64code=);}`
it becomes
`{background-image: url(data:image/png !important;base64,base64code=) !important;}`
!important before base64 causes an error.

**Comment by lllusion3469** [comment]
As I've already said in https://github.com/danbooru/danbooru/issues/4385#issuecomment-609031825, I would propose getting rid of this behaviour altogether.

### Rationale:
1. CSS is not a regular language - there are always going to be edge cases using regex
  * some failures can be used to "opt-out" of `!important` e.g. putting the `;` on the next line
  * but others such as this one are difficult to resolve with or without editing the regex
2. [Principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment): I was personally surprised when I first found out this happened and was the reason my CSS wasn't working. As far as I can tell it's not even documented anywhere.
3. Even if it is reliably possible to do this transformation (e.g. by using an actual CSS-parser), there are a few use-cases where it's not what the user wants
  * e.g. if you want to `textarea.something { height: 500px !important; }` will prevent the user from manually resizing the textarea
  * If you want to override some of the page-CSS (e.g. to change the colors) you might not want `!important` because the there are some cases where the default stylesheet relies on specificity to override another rule. If you want to change that rule you would obviously only want to change it in cases where it applies by default, but `!important` makes this impossible - your rule would also override those other rules with higher specificity.
    When a browser has to decide between multiple rules with the same specificity, [it picks the last one](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#Specificity_2), so as long as `custom_style.css` is put below the other style sheets in `<head>` that should be enough in most cases.
4. If a user wants `!important` they can explicitly put it in the rule.
   If a user does not want `!important` they have to resort to unintended, undocumented tricks to avoid the regex matching.

### Some Possible Solutions:
* adding a checkbox to let the user decide
  * should in my opinion be set to the non-`!important`-mode for users not currently using custom css and new users
* adding a second `custom_style` without this transformation applied
* applying the transformation in-database in a migration once getting rid of the regex entirely like I described [here](https://github.com/danbooru/danbooru/issues/4385#issuecomment-609031825). I also posted a single SQL-`UPDATE`-statement there you can use if you don't want to resort to ruby.

I would personally prefer the third option:
1. in my opinion this transformation should never actually be applied - this avoids most breakage for existing custom styles without adding technical and mental baggage for the future.
   It would change their custom style to what it has essentially been all along and let them edit it directly without an intermediate layer in the future.

### Drawbacks:
* old unmaintained styles in the forum might break
* it might confuse users who don't actually understand CSS and just copy and paste in some cases

**Comment by lllusion3469** [comment]
As for a workaround: if something like
```css
#page {
  background-image: url("data:image/gif;base64,R0lGODdhAQADAPABAP////8AACwAAAAAAQADAAACAgxQADs=")
}
```

doesn't work for you (it does for me even with the `!important` in chromium and firefox) maybe something like this does:
(even though the github syntax highligher complains)
```css
#page {
  background-image: url("data:image/gif\
;base64,R0lGODdhAQADAPABAP////8AACwAAAAAAQADAAACAgxQADs=");
}
```

Or maybe it's enough to put `"` / `'` around the URL?

**Comment by evazion** [comment]
I'll just bite the bullet and stop adding `!important`. This will probably break a lot of custom CSS.
