### ISSUE TITLE
Something broke for imageboard_desourced

### ISSUE THREAD

**Issue by iDolmatov** [danbooru/danbooru#4419]
Open URL https://danbooru.donmai.us/posts?tags=imageboard_desourced get this error.
Logs:
GET https://danbooru.donmai.us/posts?tags=imageboard_desourced 500
GET https://danbooru.donmai.us/assets/application.css net::ERR_ABORTED 404

Try incognito: worked.
Try incognito login: error repeat.
Logout incognito: worked.
User ID | 418258
Level | Member

![image](https://user-images.githubusercontent.com/19782385/79618410-6b2a6380-8123-11ea-88d7-73d2f87ae2d7.png)
![image](https://user-images.githubusercontent.com/19782385/79618420-71b8db00-8123-11ea-8de9-6bd02e6596d5.png)

**Comment by BrokenEagle** [comment]
This is a non-issue. You're searching a tag which has a low incidence and using a high limit of posts per page, and since your account is Member-level you have a search timeout of 3 seconds ([Help:Users](https://danbooru.donmai.us/wiki_pages/help:users)) which is what is happening. The reason you're not experiencing this when incognito is because the default limit for that is 20 posts per page. If you lower the limit for the search using the `limit:` metatag it'll be less likely to timeout ([Help:Cheatsheet#Limit](https://danbooru.donmai.us/wiki_pages/help:cheatsheet.html#dtext-n2-6)). You can also use range qualifiers as well to lower the number of posts to search through ([Help:Cheatsheet#RangeQualifiers](https://danbooru.donmai.us/wiki_pages/help:cheatsheet.html#dtext-n2-2)).
