### ISSUE TITLE
Use only seen characters for post flag/appeal reason limit

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4429]
The 140 character count limit applies to all of the characters in the reason, which pretty much makes it damn near impossible to use any kind of DText formatting.

https://github.com/danbooru/danbooru/blob/94180d77b42e169c8cf6dcd301cdf01a3770a4a5/app/models/post_appeal.rb#L9
https://github.com/danbooru/danbooru/blob/94180d77b42e169c8cf6dcd301cdf01a3770a4a5/app/models/post_flag.rb#L13

This would be like Twitter including the hashtag and @ mention links as part of their character limit count. Instead, it should work like Twitter, i.e. the character limit should apply only to the **seen** characters and not the unseen DText formatting  characters.

**Comment by evazion** [comment]
Wontfix. This limit is intentionally restrictive to 1) encourage short reasons that are easy to skim while going through dozens or hundreds of other appeals on the /post_appeals index and 2) to discourage reasons that take up too much space or that look bad on mobile.

Only ~7% of appeals go over this limit, and I don't see any that are because of Dtext.

See post 3849226 on mobile (highly nsfw) for what motivated this limit.
