### ISSUE TITLE
Batch Upload with Twitter links doesn't fetch enough information

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4430]
Opening images from the batch upload window fetches images with a source different from the tweet itself. It also is unable to fetch artist information and the tweet's commentary.

**Comment by BrokenEagle** [comment]
I'm not experiencing this myself. I just used the batch bookmarklet on a Twitter post, and it fetched the correct thumbnails with the correct upload links for both.

https://danbooru.donmai.us/uploads/batch?url=https%3A%2F%2Ftwitter.com%2Foze511111%2Fstatus%2F1245012964954046466

Can you fully demonstrate the issue, such as what URL links were used, along with screenshots of the problem?

**Comment by nonamethanks** [comment]
Was replicated in https://danbooru.donmai.us/posts/3918379. I've experienced something similar myself in the past, will try to see if I can figure out what's causing this.

**Comment by luni3359** [comment]
Here are some screenshots showing what I mean
![2020-05-20_210850](https://user-images.githubusercontent.com/16832398/82515608-3de42300-9ade-11ea-95b0-0e0d9b1188b7.png)
![2020-05-20_210407](https://user-images.githubusercontent.com/16832398/82515614-42104080-9ade-11ea-8174-0e01f47c9ac7.png)

**Comment by BrokenEagle** [comment]
Oh yeah, now that I see what URL you were using the bookmarklet from, it's clear that the `?s=20` at the end of the batch URL is what is causing the issue.

- **URL:** https://twitter.com/oze511111/status/1245012964954046466?s=20
- **Batch:** https://danbooru.donmai.us/uploads/batch?url=https%3A%2F%2Ftwitter.com%2Foze511111%2Fstatus%2F1245012964954046466%3Fs%3D20

That's the same link as the above, only with that additional nonessential Twitter parameter.

As seen by the following, it now has the Twitter image as the source instead of the tweet URL.

![image](https://user-images.githubusercontent.com/21149935/82522337-f5c50080-9add-11ea-860f-f2a31a32dcb6.png)

**Comment by luni3359** [comment]
No, I still get this issue. Works on Chromium but not on Firefox.

**Comment by luni3359** [comment]
Turns out that the problem seems to be caused due to an extension called ClearURLs stripping the ref parameter.
