### ISSUE TITLE
Add additional DText syntax

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4449]
- [x] 1. `<hr>` tags with `[hr]`

    https://github.com/r888888888/dtext_rb/issues/38

- [x] 2. Pull requests with `pull #1234`

    This is to help distinguish between issues that have been reported, and fixes that have been submitted. Because it's currently a little confusing.

- [x] 3. Commits with `commit #abcdef1`

    So that specific commits can be talked about.

- [x] 4. More fragment markers

    - Any block item
        - quote, expand, table, thead, tbody, tr, td, code spoiler
        - Example: `[tr#row-link]`
    - Any list item
        - Example: `*#list-link List item`
    - A new inline tag
        - Example: `[link=inline-link]Link here[/link]`
        - These would not render anything visible, just create a `<span>` wrapper with an ID

<br>

- [ ] 5. More fragment links

    - Wiki links
        - Example: [[Help:API#testing]]
    - Maybe topic/post fragment links?

<br>

- [ ] 6. Specify the type of code for code blocks

    **Example:** 

    ```
    [code=javascript]
    window.location = window.location;
    [/code]
    ```

**Comment by evazion** [comment]
1: The `[hr]` tag was added in https://github.com/danbooru/dtext_rb/commit/b6f8c6c4eb2445ca472efccb2836d3b3c2d7fe45

2 and 3: The `pull #1234` and `commit #abcdef1` tags were added in https://github.com/danbooru/dtext_rb/commit/612db1d96c1041eb554c204d417fa04d1927e390.

4: This is wontfix. I think you should only be able to link to header elements. If you want to link to a particular section in a wiki page or forum post, you should make a header for it. I don't like the idea of linking to any random place on the page. It should be clear where links go.

5: This is a good idea but difficult because `#` is a legal character in tags. For example, `[[htol#niq:_hotaru_no_nikki]]` is a real tag with existing links to it that we can't break. Some alternative syntax is needed. Maybe `[[Help:API]]#testing` or `[[Help:API]](#testing)` or `[[Help:API#Testing]]` (with a rule that the fragment ID must be capitalized, otherwise it's interpreted as a tag name).

6: I guess this could be useful for optional clientside syntax highlighting, but adding syntax highlighting to Danbooru itself would probably be more complexity than it's worth.

**Comment by BrokenEagle** [comment]
## Re: 4

The use case I was thinking of for # 4 was that of a wiki page citation redirect.  For instance, currently I include the citation sources on many wiki pages as indicated by a [1], [2], etc, and then place all of the actual links for those in the **External links** section.  The fragment link I give those numeric markers all point to the **External links** header, whereas most wikis I've seen redirect to the actual citation and not the section of citations.

Not sure there's much of a demand for such, but that's how I've seen it elsewhere so I thought I would at least throw the idea out there.

## Re: 5

How about using the pipe since it's already a special character?

1. [[wiki]] 
    - no custom name
    - no fragment link
2. [[wiki|text]]
   - custom name
   - no fragment link
3. [[wiki|text|fragment]]
   - custom name
   - fragment link
4. [[wiki||fragment]]
    - no custom name
    - fragment link

There are currently only 13 wikis and 10 tags with pipes in the name, so how about we just say we don't care about those and make users use textile links for them if they really want to link them.

## Re: 6

Ah, I was thinking this might be an easy fix since GitHub already does it. I thought that maybe there would be some kind of Ruby gem or Javascript library which only had to be slapped into place in order to get it working.

**Comment by evazion** [comment]
I went with the syntax `[[touhou#Games|List of Touhou Games]]` to produce [List of Touhou Games](https://danbooru.donmai.us/wiki_pages/touhou#dtext-games). This is the syntax Wikipedia uses, and I want to stay close to that. The rule is that the fragment ID must start with a capital letter, otherwise it's treated as part of the tag. So `[[htol#niq:_hotaru_no_nikki#Characters|Hotaru no Nikki Characters]]` produces [Hotaru no Nikki Characters](https://danbooru.donmai.us/wiki_pages/htol%23niq:_hotaru_no_nikki#dtext-characters).

I added this syntax specifying the language of code blocks:

    [code=ruby]
    puts "Hello"
    [/code]

    ```ruby
    puts "Hello"
    ```

This doesn't actually do anything but add a `data-language="ruby"` attribute. This can be used for clientside syntax highlighting with something like [Highlight.js](https://highlightjs.org/). I don't really want to add this natively because I don't think it's worth adding yet another dependency for something that would be rarely used.

For citations, we should some sort of dedicated syntax similar to Markdown:

```
This is a Markdown reference link [1]. At the bottom are the link reference definitions [2].

h4. External links

* [1]: https://github.github.com/gfm/#reference-link
* [2]: https://github.github.com/gfm/#link-reference-definitions
```
