### ISSUE TITLE
Unify commentary of posts coming from the same source

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4450]
In Pixiv they all share the same commentary, so changes should replicate across all of them (or alternatively, they should all share the same commentary).

**Comment by luni3359** [comment]
This would also help decrease the count of ``commentary_request`` posts.

**Comment by BrokenEagle** [comment]
This shouldn't be automatic though, instead it should be something that users could manually apply. The reason being, to cite an example, is that I myself frequently upload from Pixiv using an artist's image dump from Twitter, but then I give those posts the artist commentary from their Twitter sources instead, especially since the Pixiv commentary is usually worthless in such cases.

**Comment by BrokenEagle** [comment]
Not sure that this should still be open, given the rejection of the PR.
