### ISSUE TITLE
Add more visibility to comment linking

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4451]
For a long time I've been entering developer mode to copy the comment id to link to it. It only now occurred to me that there must be a simpler way to do it, which was when I found out that the "N time ago" timestamp was clickable.

**Comment by nonamethanks** [comment]
Forum posts need it too.
The only reason I still use DanbooruEX aside from tag scripting is because it displays "comment #<number>" next to comments, which is easily copypastable into Discord.

**Comment by BrokenEagle** [comment]
Just add a **Permalink** link to the left of the "Reply" link for both comments and forum posts which will have the full URLs. For this, I'd personally prefer the `/forum_posts/XXXX` and /comments/XXXX` links since those are a shorter format and would be better for copy/pasting on character limited sites like Twitter.

Additionally, add the text "forum #xxxx" and "comment #xxxx" underneath the timestamp to facilitate easy usage with DText and with Fumimi on Discord.

**Comment by nonamethanks** [comment]
The comment part was fixed in bed5fdafb8c485bf03500ec5a918c339f7a63304, now all that's left is the forum links.
