### ISSUE TITLE
Disabling cropped thumbnails is broken

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4460]
Disabling cropped thumbnails produces blurry thumbnails. We set the thumbnails to `width: 33.3vw`, which forcibly upscales them if they're smaller than that. Instead we should set `max-width: 33.3vw`.

![image](https://user-images.githubusercontent.com/8430473/81812925-696a7a80-94ec-11ea-97b5-b9aa0cec898e.png)

![image](https://user-images.githubusercontent.com/8430473/81812938-70918880-94ec-11ea-87d8-946652129d96.png)

**Comment by HowWillWeRIP** [comment]
![dwdadsdasdad](https://user-images.githubusercontent.com/79837625/109478640-ca623f80-7a79-11eb-9fe6-edf4673a803a.jpg)
Disabling cropped thumbnail should also get a maximum height limit or something, since some taller image totally covers the "page next/page previous" buttons, making it impossible to go to the next page. Also they do overlap with each other which looks weird
![2f3f](https://user-images.githubusercontent.com/79837625/109479034-42306a00-7a7a-11eb-8de8-bb0f41b7427f.jpg)
