### ISSUE TITLE
Can't set sources containing commas from taglist

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4467]
"source:https://test.site/contains,commas" won't work despite being a valid url (we have real user cases: https://danbooru.donmai.us/posts?tags=source%3A*%2C* - a lot of them are deviantart).

Furthermore, attempting this causes the existing source to be emptied.

**Comment by lllusion3469** [comment]
I can't seem to reproduce this.

Neither with `source:https://test.site/contains,commas` nor with the first DA url with commas under the search result and neither on my dev environment nor with my "production" environment which even has post versions (though the setup is a bit different than upstream, I skip sqs because it's not really needed). And neither on the posts page with "edit" nor with tag-scripts.

**Comment by nonamethanks** [comment]
Huh, I actually cannot replicate it anymore. I had an url that consistently failed, but I can't find it right now. I'll close this for now, because I can't replicate it with random extractions.
