### ISSUE TITLE
Tag edit mode on posts view applies taglist to wrong post & more problems

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4468]
Steps to reproduce:
* switch to edit mode in posts view
* add status:active to a pending post -> the thumbnail is updated correctly
* add status:active to a second pending post -> the thumbnail is not updated.

**Comment by lllusion3469** [comment]
Maybe I've just messed up something on my instance but I'm experiencing something more general:
1. click on post 1 (in edit mode)
2. add tag `test1`
3. open post 1 (in new tab), see `test1` tag, no `test2` tag
4. click on post 2 (in edit mode), _not reloaded_
5. add tag `test2`
6. open post 2 (in new tab), see nothing changed
7. open post 1 (in new tab), see `test2` tag, no `test1` tag

so it seems to affect the first post you clicked on

**Comment by nonamethanks** [comment]
As it turns out, this bug is graver than I thought.

https://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=3914238
https://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=3914260

**Comment by lllusion3469** [comment]
An easy fix should probably be to replace [this line](https://github.com/danbooru/danbooru/blob/45064853de51ddaa32124844267ef18dc2b1dbef/app/javascript/src/javascripts/post_mode_menu.js#L128) with `$("#quick-edit-form").data("post-id", post_id)`.

I would probably also investigate whether there are other places where this mixup between `.attr("data-foo")` and `.data("foo")` causes problems and as I said above I would maybe even get rid of `.data()` entirely because this behaviour seems too confusing and prone to bugs.

**Comment by nonamethanks** [comment]
https://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=3914220
This one even has a fake tag version. Not sure how this is possible, but the post version was saved, but the change was not applied.
![image](https://user-images.githubusercontent.com/12946050/82232656-34688880-992f-11ea-9ffa-25935771c358.png)
![image](https://user-images.githubusercontent.com/12946050/82232674-37fc0f80-992f-11ea-8114-2ddb5127b807.png)
