### ISSUE TITLE
Check all artist URLs for duplicates when creating/editing artist entries

### ISSUE THREAD

**Issue by BrokenEagle** [danbooru/danbooru#4470]
Related to #4469. When creating or editing an artist entry, all of the lowercase normalized URLs being submitted should be checked for duplicates. This will help prevent users from creating duplicate entries. When these are found, the page should display a warning and have a checkbox to override the warning.

Other names are also something that can be checked for duplicates, and I have found matching artist entries before even when the URL check failed to find anything, however this method would produce many more false positives. Maybe instead this could be a button/link that the user could use to check for other artist matches on all of the other names.

**Comment by nonamethanks** [comment]
I think rather than a warning, it should just silently merge them to the newest submitted version (in case of conflicts between http/https, trailing slash etc). This also means there'd be no need to update all existing artists, as we could just let them be taken care of whenever they're edited again by anyone.
