### ISSUE TITLE
Weibo support

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4476]
We have around 1.8k posts with [source:\*weibo\*](https://danbooru.donmai.us/posts?tags=source%3A%2Aweibo%2A) and another 353 with [source:\*sinaimg\*"](https://danbooru.donmai.us/posts?tags=source%3A*sinaimg*).
Also [178 pages](https://danbooru.donmai.us/artist_urls?commit=Search&search%5Border%5D=id&search%5Burl_matches%5D=%2Aweibo.%2A) of weibo artist urls.

If full bookmarklet support is not possible (it should, Weibo has [an api](https://open.weibo.com/wiki/API%E6%96%87%E6%A1%A3/en)), at the very least we should be doing source normalization when mx690 samples are submitted through the upload page, and we should be normalizing artist urls too

**Comment by lllusion3469** [comment]
I experimented a bit with this base62 conversion thing and [this link](https://ofstack.com/python/10801/using-python-to-convert-sina-weibo's-mid-and-url-instances-to-each-other-(in-decimal-and-62).html) you posted about it and I noticed it seems to be wrong in some cases:
* what you posted: 4287009158189036 → GAvvlnSyP
* what the code from the site gives you: GAvvlymle (which is a 404)

In case anyone cares about the ruby code I wrote (which is a bit ugly): [gist](https://gist.github.com/lllusion3469/d5857eab784e5b535061defb8116697d)
it's mostly the same logic with some minor modifications:
* use `#divmod`
* `len(midint) / 7 if len(midint) % 7 == 0 else len(midint) / 7 + 1` → `(midint.size - 1) / 7 + 1`
  * but don't add one since `range(0,n)` ≅ `0..(n-1)`

I don't actually care about weibo, never used it once, but I was interested in what this "complex operation" and "overly complex code" was.

**Comment by nonamethanks** [comment]
Yeah, part of the reason I said it was overly complex is because I encountered some wrong cases too, and trying to investigate it seemed too time consuming, and I didn't want to add something that might have produced errors. Did you manage to fix it with your gist?

**Comment by lllusion3469** [comment]
No, I didn't actually try, though.
