### ISSUE TITLE
Deleted posts filter in advanced settings has no effect

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4512]
It has no effect on the posts displayed on search.

**Comment by bipface** [comment]
A proposed fix has been implemented in [bipface/4512](https://github.com/bipface/danbooru/tree/bipface/4512) (unittests pending), however after further discussion we discovered that there's more to this issue than meets the eye,

current behaviour is, unintuitive as it may be, as follows ( added in issue #841 ):
• *Yes* — for queries without a `status:` metatag, post queries are appended with `-status:deleted`
• *No* — for queries without a `status:` metatag, the `PostSets::Post` class filters deleted posts from the set of results

The advantage of *No* is that searches are less likely to time-out; the drawback is that you may see less than one page-full of results (like when searching `paid_reward`).
The description of the option 'Remove deleted posts from search results' doesn't really explain this at all.

Since only a handful of users currently have the option set to *Yes*, there's considerable performance implications to making *Yes* the default.

Additionally, API requests (e.g. `/posts.json`) currently respect the option based on the associated user's settings, so mass-updating the option or changing behaviour carries the risk of breaking existing clients.

Workaround is to alter requests using javascript, to automatically insert the `status:any` term where appropriate which leads to the desired behaviour from both the `PostQueryBuilder` and `PostSets` classes.
I'll probably go ahead and implement it.

**Comment by bipface** [comment]
workaround: https://github.com/bipface/danbooru-recontaminant
