### ISSUE TITLE
Show mod report notices next to reported content

### ISSUE THREAD

**Issue by evazion** [danbooru/danbooru#4525]
![image](https://user-images.githubusercontent.com/8430473/85180899-38e3d200-b24a-11ea-8576-de16295a6ad6.png)

![image](https://user-images.githubusercontent.com/8430473/85180909-426d3a00-b24a-11ea-84b3-3c31c75bd0d8.png)

This notice should be next to the flagged comment or forum post instead of at the top of the thread.

**Comment by BrokenEagle** [comment]
I think a notice should still appear at the top as well, because if it's buried down deep then moderators may not even be aware that there's an issue on that topic/post. Perhaps the notice at the top can also be a link to all of the reported content?

As for the reported content itself, it does currently draw a red border around it, but I suppose it could also use a text notice as well. Since the content gets the `data-is-reported` attribute, the users can change the styling to something different if they desire, so would the notice(s) get the same treatment?
