### ISSUE TITLE
Inconsistent behavior of search function for comments/forums

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4536]
It seems searching for more than one word at once for comments and forums returns nonsensical results.

Example with comments: https://danbooru.donmai.us/comments?search%5Bbody_matches%5D=hello+there&redirect=false
A lot of these comments don't even have the word "there" in them.
Furthermore, it should be possible to search for words in a specific order. Something like `"hello there"` specifically matching that sentence in that order, akin to google's syntax.

**Comment by lllusion3469** [comment]
I'm not an expert on postgres FTS by any means, but from what I found out:

* simple words like "the", "in", "of" (what it calls stop words) are ignored by default ([ref](https://www.postgresql.org/docs/current/textsearch-dictionaries.html#TEXTSEARCH-STOPWORDS))
  * this happens when building the index, so changing the query is useless and the index would have to be rebuilt if this were changed
  * I'm not sure how to change this, though it depends on the behavior you want in the end, there is a reason why stop words are implemented after all
* if you want the websearch-like behavior, there's [`websearch_to_tsquery`](https://www.postgresql.org/docs/current/textsearch-controls.html#TEXTSEARCH-PARSING-QUERIES) instead of the `plainto_tsquery` that's currently being used
* fwiw, [this works](https://danbooru.donmai.us/comments?commit=Search&group_by=comment&search%5Bbody_matches%5D=%2Ahello+there%2A&search%5Border%5D=id_desc) (searching for `*hello there*`), though it's more prone to timeouts (which is probably why [this](https://danbooru.donmai.us/comments?commit=Search&group_by=comment&search[body_matches]=hello+there*&search[order]=id_desc) doesn't work and straight up returns a failbooru page and not even a timeout message)
  * a `*` causes it to to use a ordinary `LIKE` comparison

[here's the code responsible](https://github.com/danbooru/danbooru/blob/b551e3634f5ae21034bed02a19a83da254350ce8/app/logical/concerns/searchable.rb#L126-L139)

but even if
