### ISSUE TITLE
Can't blacklist uploads by user

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4565]
Ref: https://danbooru.donmai.us/forum_topics/17189

**Comment by BrokenEagle** [comment]
This isn't an issue at all. A user can use `uploaderid:####` in their blacklist.

**Comment by nonamethanks** [comment]
It is an issue, because it is inconsistent with how searches and blacklists work together. Several users have expressed confusion at user:username not working, and uploader:id is not a valid search either.

**Comment by evazion** [comment]
`user:username` syntax was previously removed for performance reasons. It required an extra SQL query on the posts/index page just to lookup uploader names for username blacklists,  even though very few people actually had username blacklists.

It was also broken because blacklists have to be rewritten every time an uploader changes their username, which we didn't do.

I argue that blacklisting individual uploaders is almost always the wrong thing to do, users should blacklist tags instead.

**Comment by nonamethanks** [comment]
Alright, closing this then. Blacklisted metatags should probably be validated though in that case.
