### ISSUE TITLE
Input profile error with greyscale jpg images

### ISSUE THREAD

**Issue by lllusion3469** [danbooru/danbooru#4612]
I found a greyscale image on pixiv (can't find it right now) which resulted in the following error:

```
error: Vips::Error - icc_transform: no input profile
```

which happened in [this line](https://github.com/danbooru/danbooru/blob/9f3a9ac4e1e5c59628a65e90fb37ce4ad0d63366/app/logical/media_file/image.rb#L38).

I managed to reproduce it with [this image](https://sta.sh/02wj715866j) created with gimp (File > New > Advanced options > Colour space: Greyscale -- then export as jpeg, png won't work).

---

When uploading the file directly in the browser I get this error instead:

```
Validation failed: Md5 confirmation doesn't match Md5
```

---

This is probably due to the [hardcoded srgb input profile](https://github.com/danbooru/danbooru/blob/9f3a9ac4e1e5c59628a65e90fb37ce4ad0d63366/app/logical/media_file/image.rb#L3).

Related vips issue: [libvips / libvips # 1843](https://bit.ly/3cVmGfO)

Is it (still) necessary to specify the (fallback) input profile manually?

For a simple testcase (I may have done something wrong, though), the output without an explicit input profile and `srgb` as the export profile is exactly the same as the one with `config/sRGB.icm` as input and export profile.

From the issue:
> You can just omit the iprofile and vipsthumbnail will pick something appropriate

> Yes, libvips since 8.8 has supplied appropriate fallback profiles automatically. You only need iprofile for special cases -- eg. you somehow know that a JPG image is in Adobe98, but it has no embedded profile.

---

I guess greyscale jpeg images with an greyscale colour profile are kind of rare but currently the only way around this would be to convert it into png or an srgb image, i.e. not to use the original image.

**Comment by nonamethanks** [comment]
I've been trying to reproduce this issue in order to fix it but both your example file and another file generated with the same exact method on GIMP are successfully uploaded on my instance.

**Comment by lllusion3469** [comment]
I don't know what I was thinking back then - I should have at least added my vips version (and the fact that it was on my own instance). I should also have tested it on testbooru but after having gone through the following a few times now

1. try danbooru.donmai.us account, doesn't work
2. create new account
3. notice I can't upload yet because the account is too new
4. forget about account

I'd given up on that

So currently I'm using libvips 8.10.2-1 on arch linux and the sta.sh image above (right click -> save image as) is still broken for me, your link works, though and a new image I created in gimp since I couldn't find the old one works as well.

I don't know if I did that back then but now I also need to uncheck "save colour profile" when exporting for the error to happen.

**Comment by nonamethanks** [comment]
I'm on libvips 8.7, which is the stable version for Debian. I didn't uncheck the color profile saving when trying, that might be why. 

I'm waiting to hear back from evazion on the version danbooru uses, because there's not much point in trying to fix it if danbooru is still using a version that doesn't support a fix.

**Comment by nonamethanks** [comment]
Seems it's running on 8.7, so I guess I'll leave this issue alone for now. Commit 7a87225ac855f51679e000205e4685db9059d85e will simplify keeping track of updates.

**Comment by evazion** [comment]
See fb50788 for details. The short version is that libvips 8.7, 8.9, and 8.10 all have different behavior here. On 8.10 it's broken but on earlier versions it works.

The real solution here is to use the Docker image instead of installing manually. The Docker image has all the dependencies preinstalled and pinned to known good versions. Going forward, if you install manually, you will be expected to install the exact same versions of everything as in the Docker image. This is usually pretty difficult since it involves building a bunch of things from scratch, since most distros don't package the exact versions we need, hence the reason for the Docker image.
