### ISSUE TITLE
Differentiate between actual aliases and corrections in autocomplete window

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4650]
I've noticed several users now both in the discord and in the forum ([forum #178348](https://danbooru.donmai.us/forum_topics/12251?page=286#forum_post_178348)) being confused about the new system, because there's no difference in the autocomplete window between aliases and corrections. Admittedly I've been thrown off by it too. Some examples:

![image](https://user-images.githubusercontent.com/12946050/103448284-b677a880-4c97-11eb-8d1f-7228c6fb2adf.png)

![image](https://user-images.githubusercontent.com/12946050/103448315-47e71a80-4c98-11eb-8342-b1b6185d48ee.png)

Maybe using a different character would help differentiate them.

There are several arrow characters we could use, like ⤳ or ↠ or many others (http://xahlee.info/comp/unicode_arrows.html) that would alleviate this issue.

**Comment by evazion** [comment]
Currently misspelled tags are indicated by a dotted underline, but maybe this isn't clear enough:

![image](https://user-images.githubusercontent.com/8430473/103506311-0bdfc100-4e22-11eb-8389-bb4c9a31bc7a.png)

I changed it to a wavy red underline:

![image](https://user-images.githubusercontent.com/8430473/103506594-b0620300-4e22-11eb-994a-c447e2ac4ced.png)

That should be more intuitive.

(I'm guess the dotted underline isn't showing up for you because of custom CSS or userscripts.)

**Comment by luni3359** [comment]
This really is much better in red, thank you!!
