### ISSUE TITLE
Tag script mode sometimes adds "null" tag

### ISSUE THREAD

**Issue by kittey** [danbooru/danbooru#4663]
Using tag script mode with a blank tag script can add the tag `null` to posts you click on. The same can happen if tag script mode is used to add posts to favgroups. Other uses with only meta tags that don’t add any tags might be affected to.

I can’t reproduce either right now, though, and only found out when I cleaned `null` tags and asked the users who added them.

> MrSusher said:
> I was using the tag script mode to apply the white_pupils tag and at one point the input box cleared out without me noticing. I assume the "null" tag is what got applied when I tried to update the posts without anything in the box until I noticed it was blank. I assumed it did nothing.

[MrSusher’s null tags](https://danbooru.donmai.us/post_versions?commit=Search&search%5Badded_tags_include_all%5D=null&search%5Bupdater_name%5D=MrSusher)

> Chaos Exia00 said:
> not sure what a null tag edit means, but I was trying to use tag script mode to bulk add those pics to a fav group
> I put favgroup:<group name> for the tag and the clicked on the pics i wanted in that group

[Chaos Exia00’s null tags](https://danbooru.donmai.us/post_versions?commit=Search&search%5Badded_tags_include_all%5D=null&search%5Bupdater_name%5D=Chaos+Exia00)

**Comment by evazion** [comment]
https://github.com/danbooru/danbooru/blob/65adcd09c2d16fb56c5494ed20b050feec225865/app/javascript/src/javascripts/post_mode_menu.js#L152-L156
https://github.com/danbooru/danbooru/blob/65adcd09c2d16fb56c5494ed20b050feec225865/app/javascript/src/javascripts/posts.js.erb#L446-L449

Looks like:

* The user switched to a nonexistent tag script number.
* `localStorage.getItem("tag-script-" + current_script_id)` returned `null`.
* `Post.tag` called `String(tags)`, which returned `"null"` because `String(null)` returns the literal string `"null"` in Javascript. This differs from Ruby, where `nil.to_s` is `""`.
