### ISSUE TITLE
Is it possible to add a "comment_count" field for the API?

### ISSUE THREAD

**Issue by khoadng** [danbooru/danbooru#4687]
Something like the current "fav_count" would be awesome. Currently, I have to manually parse the HTML to count the total number of comments which is very inconvenient.

**Comment by BrokenEagle** [comment]
If you're just doing a single post at a time, then consider using the `/comments.json` endpoint using the `search[post_id]` URL parameter.

- **Example:** https://danbooru.donmai.us/comments.json?search[post_id]=1

If you're doing multiple posts at a time, then just include the comments via the `only` parameter and then count those.

- **Example:**  https://danbooru.donmai.us/posts.json?only=comments

For a list of all available includes on posts:
- https://danbooru.donmai.us/wiki_pages/api:posts

For a more thorough explanation of the **only** parameter:
- https://danbooru.donmai.us/wiki_pages/help%3Acommon_url_parameters#dtext-only

**Comment by khoadng** [comment]
Exactly what I needed, didn't know you could do that. Many thanks.

**Comment by nonamethanks** [comment]
I want to add, you can pass a limit parameter (max value 1000) to get all comments in one single call, like [this](https://danbooru.donmai.us/comments.json?search%5Bpost_id%5D=1&limit=1000), since it's very unlikely we'll have a post with more than 1000 comments any time soon (post 1 has 248 comments).

**Comment by khoadng** [comment]
Hey @nonamethanks, 

Thanks for the useful info! I have a few questions if you don't mind.

1. Can I pass that **limit** parameter with the **only** parameter, like [this](https://danbooru.donmai.us/posts.json?only=comments&limit=100)? I tried it but it didn't work. 

2. If we can't pass the **limit** parameter, what is the total number of records that are returned by the API? Is it a fixed number like the default 20 that you guys usually do?

**Comment by nonamethanks** [comment]
Yes, only and limit are compatible. You don't see anything because you're not excluding posts without comments. [See this example url](https://danbooru.donmai.us/posts.json?only=id,comments&tags=commenter:any&limit:200), which filters by posts where anyone commented. Also keep in mind "only" is a whitelist filter, it only returns the parameters you specify and nothing else, so you need to explicitly add everything you need. If you want id, created_at and comments you need to use "only=id,created_at,comment", etc.
Just a note: in the case of /posts, the **limit** parameter in the url is equivalent to a "limit:n" tag passed as part of the **tags** parameter, so [this](https://danbooru.donmai.us/posts.json?only=id,comments&tags=commenter:any&limit:200) and [this](https://danbooru.donmai.us/posts.json?only=id,comments&tags=commenter:any+limit:200) are equivalent.

Keep in mind that the max value for the **limit** parameter is 200 for /posts, and 1000 for every other endpoint.

**Comment by khoadng** [comment]
Got it, I will keep that in mind. Thanks again, you guys are really helpful!
