### ISSUE TITLE
Add support for skeb

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4691]
Opening this so I don't keep procrastinating on it.

Useful to have since skeb became mainstream recently for artists

**Comment by BrokenEagle** [comment]
The vast majority of Skeb users seem to enable the setting that pastes a big "SAMPLE" right over the image making them worthless as uploads. As such, I'm not sure how used such a function will be or how worth it will be to maintain.

**Comment by nonamethanks** [comment]
There's still a lot of posts without watermark, see https://danbooru.donmai.us/posts?tags=source%3A*skeb*

**Comment by BrokenEagle** [comment]
I see. 215 over the past year isn't a whole lot., nor is the 248 total.
- https://danbooru.donmai.us/counts/posts?tags=source%3A%2Askeb+age%3A..1y
- https://danbooru.donmai.us/counts/posts?tags=source%3A%2Askeb

For reference, Tinami currently has 42 over the last year and 1054 total, but it didn't get supported (issue #2818).
- https://danbooru.donmai.us/counts/posts?tags=source%3A%2Atinami+age%3A..1y
- https://danbooru.donmai.us/counts/posts?tags=source%3A%2Atinami

I just know that from my own experience, that I check an artist's Skeb whenever I find them, and thus far I've only found 2 myself without the "SAMPLE" out of probably at least a hundred, which is why I brought up my original point.

**Comment by nonamethanks** [comment]
Half of those were uploaded over the last 3 months. Skeb only recently went fully public, hence why it got a boost in popularity.

In any case, I've seen people complain before that the lack of support is why they don't actively upload from there, and there's no real cost in having support for it since if it breaks and nobody is interested in fixing it, support can simply be dropped since strategies are fully modular.
