### ISSUE TITLE
user autocomplete contains links to /posts

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4698]
- go to [/users](https://danbooru.donmai.us/users)
- in the *Name* field, enter `bipfa`
- autocomplete list appears
- middle-click on the `bipface` entry
→ a new tab is opened at `/posts?tags=bipface`, as if `bipface` were a tag

**Comment by nonamethanks** [comment]
The issue is that https://github.com/danbooru/danbooru/blob/054ac51d471b192cdc5136b82bb1a5c939bd7332/app/javascript/src/javascripts/autocomplete.js.erb#L152-L155 
here we don't make any distinction between types of autocomplete. I guess there should be a block to define the path, rather than defaulting to "/posts?tags="
