### ISSUE TITLE
pretty-printed test results from CI

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#4712]
currently the only way to examine test results in github CI builds is to read the command-line output;

in [this branch](/bipface/danbooru/tree/bipface/testreport) i had a go at adding a workflow step to render the junit XML output into HTML, which is output as a build artefact:
[/bipface/danbooru/actions/runs/546275347#artifacts](/bipface/danbooru/actions/runs/546275347#artifacts) → [test-report.zip](https://github.com/danbooru/danbooru/files/5940455/test-report.zip)

the result seems okay – if you fiddle with the filters at the top it's reasonably usable

all i've done here is [install the `xunit-viewer` NPM package](/bipface/danbooru/blob/12046af08ab6d57ce6ecde6e7d92aaa66fc9fc9c/.github/workflows/test.yaml#L90) which generates the HTML, then output the `test/reports/` dir as an artefact.

i'd understand if you want to take a different approach for integrating this step in the test run, but this should at least provide an idea

**Comment by evazion** [comment]
Github has since added a job summary feature that lets you output test results directly in Github [1]. It also supports annotations that let you link the file and line number for each failing test.

I tried various premade Github actions to do this ([2][3][4]), but couldn't find one that I didn't have some problem or another with, so I made my own simple script to output test results in Github format.

1: https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/
2: https://github.com/marketplace/actions/junit-report-action
3: https://github.com/marketplace/actions/publish-test-results
4: https://github.com/marketplace/actions/test-reporter
