### ISSUE TITLE
Related tags checkboxes don't work properly on some phones (iOS)

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4746]
Reported by Fredgido and Randeel on Discord. Related tags need to be tapped twice to be selected.

![image](https://user-images.githubusercontent.com/12946050/109727362-845dc680-7bb4-11eb-97b6-f4535b4a4d78.png)
First tap makes the checkbox show, and second tap selects it, for every single tag.
The issue seems to happen on iOS, but PhoenixG also mentions having a similar issue sometimes on an old version of Android.

**Comment by evazion** [comment]
The fix is to use `@media (hover: hover) { ... }` media query to only hide the checkboxes if the device supports hovering (i.e. it's a computer with a mouse, not a touch device). Some mobile devices use a tap to emulate hovering.

The reason these checkboxes exist is to indicate that clicking the tag toggles it on or off. Normally when you have a list of tags, clicking the tag does a tag search,. The checkbox is to indicate that related tags work differently, which isn't obvious if you've never used related tags before. The reason they're hidden for unselected tags is to make them less obtrusive, and to make selected tags stand out more.
