### ISSUE TITLE
"status:any" breaks a/d shortcuts for pools

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4757]
When there's a search query, A/D prioritizes the next post in this search instead of pools. At least for basic searches such as "status:any", pools should have priority in the navigation.

Example: https://danbooru.donmai.us/posts/4400771?q=status%3Aany

**Comment by evazion** [comment]
Switching the navigation context would be unexpected and surprising behavior. Imagine:

* You're on the front page.
* You click a post.
* You start navigating between posts on the front page with A/D.
* Suddenly you're navigating inside a pool. Why? Because you hit some random post that happened to be in a pool so now you're navigating the pool instead of the front page.
* You try to use A/D to go back but you can't because now you're inside the pool and A/D does something different now.

**Comment by nonamethanks** [comment]
Well, I'd argue it's surprising how it works right now, because before this kind of search did not create an interactive navigator, just a greyed out one, so pool navigation worked fine.
