### ISSUE TITLE
"VipsIcc: Couldn't link the profiles" for certain pics

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4762]
https://pbs.twimg.com/media/ElFjJTdVgAAJ_zi.jpg:orig
![image](https://user-images.githubusercontent.com/12946050/110993187-41031500-8377-11eb-84e0-6c062e3dcb1b.png)

**Comment by nonamethanks** [comment]
As with other profile issues, investigating this issue is a pain because danbooru uses system libvips, not the latest, so it could be a bug that's already been solved in the latest release of the library.

**Comment by evazion** [comment]
The fix here is to fully containerize the app. Run everything inside Docker in production so that libvips and other external libraries are bundled with the app instead of using system versions.

We already have a Dockerfile and automatic Docker builds, so most of the building blocks are there, the final step is migrating to actually using containers in production. Which basically means migrating from the current deployment system (using Capistrano and Ansible to SSH into a bunch of servers and run a bunch of commands on them) to a big boy container orchestration system like Kubernetes or Nomad. In the best case this makes deployment easier, in the worst case it introduces exciting new classes of problems and points of failure.

**Comment by evazion** [comment]
This works on libvips-8.10.6 but not on 8.9.1:

```
(rails:1117600): VIPS-WARNING **: 00:41:36.759: icc_transform: intent 1 (relative) not supported by input profile; falling back to default intent
Vips::Error: VipsIcc: Couldn't link the profiles

from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-vips-2.1.3/lib/vips/operation.rb:214:in `build'
```

It looks like this image has some weird embedded color profile that older versions of libvips can't handle.

This should be working on https://betabooru.donmai.us, which is running the Docker image under Kubernetes so it has libvips-8.10.6. This will be fixed once we graduate to Kubernetes in production. Betabooru has been running successfully under Kubernetes for a few months now, so now it's mostly a matter of deploying some new servers and flipping the switch.

**Comment by nonamethanks** [comment]
Can confirm, I replaced <https://betabooru.donmai.us/posts/4233486> with the original via the betabooru instance and it worked.

**Comment by evazion** [comment]
I'll go ahead and closed this as fixed.
