### ISSUE TITLE
Discord: regression with posts command

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4766]
You cannot search for more than two tags with /posts now, a regression from before, I guess because the search is being done as anonymous.

![image](https://user-images.githubusercontent.com/12946050/111074318-bf2ffa80-84e2-11eb-9670-ff77690055d6.png)

**Comment by nonamethanks** [comment]
Counts is also broken: 
![image](https://user-images.githubusercontent.com/12946050/111078782-7cc4e880-84f7-11eb-8581-5db52cfac3fa.png)

**Comment by nonamethanks** [comment]
Another issue is that pasting tags or in general writing them without first using autocomplete to select the "tags" option won't use the tags. Try writing /posts and then pasting "bara limit:1": it will ignore the tags part. Not sure if this can be solved on our side, it's just discord having a terrible integration.

**Comment by evazion** [comment]
> You cannot search for more than two tags with /posts now, a regression from before, I guess because the search is being done as anonymous.

Fixed in 28c0a48117aac930d65fe351673fc2a6ce335941.

> Another issue is that pasting tags or in general writing them without first using autocomplete to select the "tags" option won't use the tags. Try writing /posts and then pasting "bara limit:1": it will ignore the tags part. Not sure if this can be solved on our side, it's just discord having a terrible integration.

This is a limitation of slash commands. Discord requires you to write `/posts tags:touhou` instead of `/posts touhou`. If you write `/posts touhou` then Discord apparently ignores the arguments and we never see them.

There may be an issue about this in their Github but I can't find it: https://github.com/discord/discord-api-docs/issues?q=is%3Aissue+label%3A%22slash+commands%22

Despite the limitations I think slash commands are worth it. They have a number of advantages over traditional commands:

* Writing commands is easier. You just register a command then Discord sends you a HTTP request whenever anybody uses the command. Then you just respond to the HTTP request like a normal HTTP request. This is more reliable and easier to manage than running an external bot (which is yet another service I have to run on top of all the other services I need to keep running for Danbooru).
* Tighter integration with Danbooru is possible. Commands are handled directly by Danbooru, so they have direct database access instead of having to go through the API. This means it's possible to do things like look up your Danbooru account when you run a Fumimi command and perform actions under your account.
* Commands are easier to discover. Just type `/` and Discord shows you all available commands and how to use them. We don't need separate documentation or `--help` options or `/help` commands to explain all the commands available.
* It's possible to make Fumimi's commands into global commands that work on any server you're in. This is good advertisement for Danbooru and frankly it makes Fumimi more worthwhile to work on when it's not just a bot used by a few people in a single server.

**Comment by nonamethanks** [comment]
Found the issue, it's https://github.com/discord/discord-api-docs/issues/ 2585
