### ISSUE TITLE
Normalized artist links of Hentai-Foundry, Pawoo, Twitter, and ArtStation aren't lowrecased

### ISSUE THREAD

**Issue by 7nik** [danbooru/danbooru#4821]
Hentai-Foundry, Pawoo, Twitter, and ArtStation are case-insensitive to user names, so links to user profiles can be safely lowercased. But currently, there are a lot of profile links to these sites that contain non-lowercased user names.

[Hentai-Foundry](https://danbooru.donmai.us/artist_urls?commit=Search&search%5Bnormalized_url_matches%5D=%2F.%2Ahentai-foundry.%2A%5BA-Z%5D.%2A%2F&search%5Border%5D=id) - almost 800 such links;
[Pawoo](https://danbooru.donmai.us/artist_urls?commit=Search&search%5Bnormalized_url_matches%5D=%2F.%2Apawoo.%2A%5BA-Z%5D.%2A%2F&search%5Border%5D=id) - over 3k;
[Twitter](https://danbooru.donmai.us/artist_urls?commit=Search&search%5Bnormalized_url_matches%5D=%2Fhttp%3A%5C%2F%5C%2Fwww.twitter.com%2F.%2A%5BA-Z%5D.%2A%2F&search%5Border%5D=id) - 8 but quite recent;
[ArtStation](https://danbooru.donmai.us/artist_urls?commit=Search&search%5Bnormalized_url_matches%5D=%2F.%2Awww.artstation.%2A%5BA-Z%5D.%2A%2F&search%5Border%5D=id) - 14, some are recent as well.

Fixing this issue would allow Translate Pixiv Tags to use the `normalized_url_array` field instead of `normalized_url_lower_array` on the `artist_urls` endpoint that would speed up network request from 3-5s to 200-500ms and overcame timeouts for regular members.

**Comment by evazion** [comment]
Fixed by making the artist finder case insensitive. That way URLs can be stored in the right case, but the case can be ignored during artist lookup.

To use it you need to do this:

* https://danbooru.donmai.us/artists.json?search[url_matches]=https://twitter.com/AKI_kikumugi

instead of
  
* https://danbooru.donmai.us/artist_urls.json?search[normalized_url_lower_array][]=https://twitter.com/AKI_kikumugi

Currently `url_matches` only supports one URL at a time, but that could be changed.
