### ISSUE TITLE
DanbooruBot not properly handling BUR aliases when target tag has a wiki

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#4829]
**Problem**
When making an alias, Tax X → Tag Y, if Tag Y already has a wiki regardless or not it has posts, DanbooruBot ignores the wiki on Tag X and simply deletes it instead of merging both.

The existence of a wiki on Tag Y also causes DanbooruBot to not try to replace the old tag with the new one in wikis that use it. At the very least it should force a rename when it's the first part of one of these: `[[replace_me|← The part of the left]]`

**Proposal:**
If the body is empty on the wiki of Tag Y, DanbooruBot should copy the body of Tag X and put it over in Tag Y's wiki, like a merging operation.

**Comment by evazion** [comment]
>When making an alias, Tax X → Tag Y, if Tag Y already has a wiki regardless or not it has posts, DanbooruBot ignores the wiki on Tag X and simply deletes it instead of merging both.

When two wikis have conflicting content, the content of old wiki is deleted and the new wiki is left as-is. The bug was that this happened even when the new wiki was blank.

>The existence of a wiki on Tag Y also causes DanbooruBot to not try to replace the old tag with the new one in wikis that use it. At the very least it should force a rename when it's the first part of one of these: [[replace_me|← The part of the left]]

This isn't what happened. It didn't rewrite `[[Emilia LeBlanc|Emilia LeBlanc (Evaine), the Deceiver]]` because it didn't know how it should be rewritten. It doesn't know that, when renaming `emilia_leblanc` to `leblanc_(league_of_legends)`, that `leblanc_(league_of_legends)` should be properly written as `LeBlanc_(League_of_Legends)` and not `Leblanc_(League_Of_Legends)`. It skips wiki links that have mixed capitalization, because it doesn't know how the capitalization should transfer to the new tag. These cases are left for the user to fix. It also doesn't know how the `Emilia LeBlanc (Evaine), the Deceiver` part of the link should be rewritten. Links with custom link text usually need to be fixed manually.

**Comment by luni3359** [comment]
> This isn't what happened. It didn't rewrite `[[Emilia LeBlanc|Emilia LeBlanc (Evaine), the Deceiver]]` because it didn't know how it should be rewritten. It doesn't know that, when renaming `emilia_leblanc` to `leblanc_(league_of_legends)`, that `leblanc_(league_of_legends)` should be properly written as `LeBlanc_(League_of_Legends)` and not `Leblanc_(League_Of_Legends)`.

lol I'm not talking about capitalization, that's something I changed afterwards. Check the [wiki history](https://danbooru.donmai.us/wiki_page_versions/365376) to see what I'm talking about.

There's [[partA|partB]]. On a wiki, partB is what the user reads as text, while partA turns into the link to the tag. When the bot changed the name of the tags, it missed changing the tags of 3 characters as seen in blue. The rest of the characters in the BUR were changed without issues.

I presume that it's because those tags already had been, or were populated already by the time the BUR went through.
