### ISSUE TITLE
NewRelic: duplicate results when grouping by request.params.tags

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4900]
If you do a simple `select count(*) from Transaction since 7 days ago facet request.params.tags limit 500` you'll see that there's a lot of duplicate results. I'm assuming this is because of stray spaces somewhere. Those parameters should ideally be trimmed before being sent to NewRelic.

**Comment by evazion** [comment]
You can use `search.query` to get the normalized query:

```
select count(*) from Transaction since 7 days ago facet search.query limit 500
```

This strips whitespace, converts tags to lowercase, applies aliases, removes duplicate tags, and normalizes tag order.

There was a bug where `search.query` wasn't logged if the search failed, because of a search timeout or a tag limit error. This has been fixed in 1518c3c .
