### ISSUE TITLE
Use downscaled 720x720 thumbnails for gigantic post previews

### ISSUE THREAD

**Issue by SuzakuMedli** [danbooru/danbooru#4944]
Large, huge, and gigantic post previews all use 360x360 thumbnails by default, and 720x720 thumbnails when your device has a high pixel density ratio. Gigantic post previews should use 720x720 thumbnails by default, regardless of pixel density.

**Comment by evazion** [comment]
Wontfix:

* I don't really want to add more size options. Five choices is already a lot.
* I don't want to make the biggest option 720x720 and the next biggest 360x360. It's too big of a leap.
* 720x720 thumbnails are in webp format, which not all devices support. This is fine when they're a transparent upgrade over 360x360 thumbnails, but not fine when they're meant to work for everybody.
* 720x720 thumbnails are generated at a lower quality level than other thumbnails. This is to save bandwidth. This is unnoticeable at 360x360 size, but very noticeable at full size.
* 720x720 thumbnails need a 1440x1440 variant for high density screens, otherwise thumbnail quality is noticeably worse.
* Browsing at 720x720 size isn't very practical. You can only see 2 images per row at 1920x1080 and 1 per row at smaller screen sizes. Most users, around 80%, have a screen smaller than 1920x1080.

I added a https://danbooru.donmai.us/posts?size=720 option, but this is a hidden option not exposed in the UI.

**Comment by SuzakuMedli** [comment]
Sorry for the confusion, I wasn't asking for new higher-resolution thumbnail sizes to be introduced, I just figured that since large and huge post previews use 360x360 thumbnails downscaled to 225 and 270 respectively, gigantic could use 720x720 thumbnails downscaled to 360. 360x360 thumbnails are currently being used for all three, unless the user has a high pixel density screen.

In other words, I'm asking for the site to use `<source type="image/webp" srcset="https://cdn.donmai.us/720x720/image.webp 1x">` when using gigantic post previews, which would allow browsers to transparently upgrade the thumbnails used for gigantic post previews to 720x720 if WebP is supported, and fall back to 360x360 if it isn't.
