### ISSUE TITLE
Highlighed replacements

### ISSUE THREAD

**Issue by lordnord** [danbooru/danbooru#4948]
After #4946  it will be impossible to tell from the post page if there was a replacement or not. So I suggest to highlight **Replacements** link with different color if there was a replacement. Or to add some symbol to it.

Examples:
![image](https://user-images.githubusercontent.com/2413865/147689682-f4fb1bc9-e4f9-46f0-8577-e2ba367ba606.png)
![image](https://user-images.githubusercontent.com/2413865/147689830-171ea7ba-5763-4677-8fd6-364449d0fec5.png)

**Comment by BrokenEagle** [comment]
Well, the same is true of all of the other categories except for tags (which are mandatory). Moderation events don't always exist, and pools/notes/commentaries can be deleted, which wouldn't be apparent from the post itself. If this gets done, then those other categories should be considered as well.

Also perhaps instead of an asterisk, include the number of items as well, unless of course the SQL query for that is more expensive then just testing the existence. If just an existence test is done, then all of those links could be given popup tooltips which will query the events, and list the total number along with the last update (and maybe user).

**Comment by evazion** [comment]
I removed the `Replacements` link and put replacements under `Moderation` instead. This way you only have to check one page.

An indicator would add overhead to every pageview that I don't think is worth it considering that most posts don't have replacements and most users don't need to check when a post is replaced.
