### ISSUE TITLE
And+or search?

### ISSUE THREAD

**Issue by akunohomu** [danbooru/danbooru#4949]
On Gelbooru I can do a search like this `{new_year ~ 2022} {medium_breasts ~ large_breasts}` which means "posts that have (`new_year` OR `2022`) AND (`medium_breasts` OR `large_breasts`)".

On Danbooru I can do searches like `~new_year ~2022` to find posts with either of those tags. Is performing the above type of search possible? I can't find it in the cheat sheet.

Apologies if this has been asked before, it's hard to google the words 'and' and 'or'.

**Comment by nonamethanks** [comment]
No, this is not currently possible on danbooru.

**Comment by BrokenEagle** [comment]
It's possible with Rails/Postgres I believe. It has supported OR clauses for a while now.

The difficulty lies with parsing the tag string using an additional set of tokens, which would require restricting the list of available characters for use in tag names. Plus the query builder would have to almost be completely rebuilt in order to group explicitly/implicity by AND/OR rules.
