### ISSUE TITLE
Allow for configurable initial upload limits

### ISSUE THREAD

**Issue by GiantFrog** [danbooru/danbooru#4963]
I am happy to implement this myself if people think it is a good idea!

Right now, in /app/logical/upload_limit.rb, a user is given 1000 initial points to determine their upload level. In addition, the upload_slots method will always add 5 slots, even to a level 0 user. I propose keeping these default values unchanged but allowing them to be customized in the config file if desired. This way, a server owner could tighten or relax the rules as they see fit, or even disallow uploads by default for new accounts.

**Comment by BrokenEagle** [comment]
As a general issue, should most of the constants used by Danbooru be moved to the config file?

**Comment by GiantFrog** [comment]
I mean, my vote is yes, of course! I'm just not familiar enough with the software to know where other constants would be.

**Comment by BrokenEagle** [comment]
Ah, sorry. I left that comment as something for the main developers to see and think about.

**Comment by evazion** [comment]
Fixed in #4964.

**Comment by evazion** [comment]
Most constants are hardcoded for simplicity. The Danbooru codebase is first and foremost designed for the Danbooru website, and the Danbooru website mostly doesn't need this kind of runtime configuration.

You can use Danbooru's code to host your own booru, but this is not a primary design goal. A lot of policy decisions like how the moderation system should work or how user privileges should work are very site-specific and will likely require manual customization.

I prefer to minimize the number of configuration options because each additional option is a burden. It's a maintenance burden upstream and a cognitive burden downstream. For each option, you have to understand what it does, whether you should change it, and what value you should change it to. It's more difficult to get started when there are dozens of configuration options and you have to understand all of them.

For upload limits in particular, you can't freely change these values at runtime after users have been created. When a user is created, their upload points are set to an initial value. If you later change that value, it won't affect existing users. You'd have to go into the console and reinitialize the upload limits of all existing users. Which is possible, but it's more stuff that needs to be documented and understood, which gets back to the point that each additional option is additional cognitive overhead.
