### ISSUE TITLE
Search for an artist by weibo.cn URL shows no results

### ISSUE THREAD

**Issue by lordnord** [danbooru/danbooru#4968]
I tested it on several cases. 
If URL looks like this https://weibo.cn/u/1852049217 search returns nothing.
It works for https://weibo.com/{username} links though.

**Comment by evazion** [comment]
Fixed by 223742c3658f52ce28d1a36f5c6d1e0eac9487e9, 133c45ee295cac082c32ddd502f25924dc144b7a, 1d9a15a119070001da43b98b7062d90d3c8f97c9, and a78b6528d.

There are three types of Weibo profile URLs:

* https://www.weibo.com/u/5399876326
* https://www.weibo.com/p/1005055399876326
* https://www.weibo.com/chengziyou666

`https://www.weibo.com/u/5399876326` is the one that artist entries should contain for artist finding to work.
