### ISSUE TITLE
-approver:username implicitly adds approver:any

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#4978]
[status:deleted -approver:nonamethanks](https://danbooru.donmai.us/counts/posts?tags=status%3Adeleted+-approver%3Anonamethanks+) returns 18k posts, but status:deleted has 281k posts, which would imply I approved 260k now deleted posts. It seems excluding an approver from a query implicitly adds "approver:any" to it.

**Comment by evazion** [comment]
We're doing this:

```
SELECT COUNT(*) FROM posts WHERE approver_id != 508240 AND is_deleted = TRUE;
```

when we should be doing this:

```
SELECT COUNT(*) FROM posts WHERE approver_id IS DISTINCT FROM 508240 AND is_deleted = TRUE;
```

or this:

```
SELECT COUNT(*) FROM posts WHERE (approver_id != 508240 OR approver_id IS NULL) AND is_deleted = TRUE;
```

The problem is that in SQL, `approver_id != 508240` doesn't include when approver_id is NULL.

This also affects other nullable fields, like parent_id (e.g. https://danbooru.donmai.us/posts?tags=-parent:1 only returns posts where parent_id is non-null).
