### ISSUE TITLE
NoMethodError when searching an old-style dead fanbox url in artist urls

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5082]
https://www.pixiv.net/fanbox/creator/40684196 causes a NoMethodError, https://www.pixiv.net/fanbox/creator/955993 instead just returns nothing but doesnt raise an exception.

![image](https://user-images.githubusercontent.com/12946050/160925462-0720ee40-6d8b-42d6-a4f6-719cdefe0309.png)

**Comment by evazion** [comment]
https://www.pixiv.net/fanbox/creator/955993 returns nothing because we convert it to https://mowiroong.fanbox.cc for artist finding purposes, and there are no artists with that URL in their artist entry. We convert it because there are more artists with `https://<username>.fanbox.cc` URLs than `https://www.pixiv.net/fanbox/creator/<id>` URLs. There is an artist [mowiron](https://danbooru.donmai.us/artists/276993), but they only have https://www.pixiv.net/users/955993 in their artist entry.

I suppose what we should do is have `profile_urls` return all possible profile URLs for the artist, then have `ArtistURL#url_attribute_matches` try all URLs instead of just one.

Note that only `/artist_urls.json?search[url_matches]=` will to convert the URL this way, `/artist_urls.json?search[url]=` will do a straight lookup.
