### ISSUE TITLE
Posts search with random=true causing too many redirects

### ISSUE THREAD

**Issue by luni3359** [danbooru/danbooru#5185]
Trying to make any query on /posts causes an infinite redirect when random=true is used as a parameter. The query goes through successfully without the random parameter.

Minimum reproducible code:
```python
import asyncio
import aiohttp
import json

auth = aiohttp.BasicAuth(login="yourusername", password="yourpassword")
headers = {'Content-Type': 'application/json'}
data = {
    "tags": "hibiki_(kancolle)",
    "random": True
}

async def main():
    async with aiohttp.ClientSession(auth=auth) as session:
        async with session.get("https://danbooru.donmai.us/posts.json", data=json.dumps(data), headers=headers) as response:
            response_body = await response.read()
            print(response.status)
            print(response_body)

asyncio.run(main())
```

**Comment by nottalulah** [comment]
Why are you sending data (post body) for a GET request? It should be params= for a GET. It's surprising that that works at all.

**Comment by luni3359** [comment]
Idk I've always used it this way and I could never find any examples online of how to use .get() with data so I just copy-pasted the same code with .posts() from the documentation and it's worked ever since.

@nottalulah After reading your comment I've gone through a long, tiring and exhaustive search (ctrl+f and google) I've found that params is indeed used. But I could have never found out without you, so thank you so much!!

That being said, since it _does_ work with other sites... _maybe_ it should work here too? Regardless, I'm going to close this issue. At least other people (if ever) can find this issue to know what to do.

**Comment by nottalulah** [comment]
Looks like the reason you get too many redirects is because the posts controller assumes a GET request will have ?random=true as a query string, and redirects you to a path where it doesn't (`/posts.json?tags=hibiki_(kancolle)+random:20`). But then on redirect the POST body still contains random=true, so it tries to redirect you again, and again, until you get an error.

I think it's an issue with aiohttp specifically, where it tries to send the POST body again on redirect. If I use other HTTP clients to send POST data in a GET request it works as expected.
