### ISSUE TITLE
Source extractors not using 60s timeout

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5241]
27d71f2727c661c42090fcb40c262fbce95dc391 was supposed to raise download timeouts to 60s but it seems it's not working. Trying to upload from Lofter will often time out and return a message

> Upload failed: \<URL\> doesn't contain any images.

I measured it in the console and it is indeed timing out after only 10 seconds:

![image](https://user-images.githubusercontent.com/26291500/186719208-df676138-d3a5-4c82-aca0-a0117d722a10.png)

The message for Lofter should probably specify it's a time out and not that the page contains no images as well.

**Comment by nonamethanks** [comment]
I think this is caused by the fact that Lofter takes more than 10 seconds to fetch the data itself before it even attemps to download. The timeout only applies to the http downloader, not to all the transactions done with the http client by our source strategies. @evazion does it make sense to raise that timeout too?
