### ISSUE TITLE
[Feature request] Skeb tags from commentary

### ISSUE THREAD

**Issue by Kikimaru** [danbooru/danbooru#5244]
Example: 
https://skeb.jp/@tokkotoritori/works/12  / https://danbooru.donmai.us/posts/5635250

Seems Skeb has a feature where tags can be embedded into the artist commentary.

**Comment by nonamethanks** [comment]
They're not real tags, Skeb tries to be smart and autolink what it thinks are common terms among requests, but it's not reliable and it can fail pretty hard.

For example one of the selected tags in your post is [ラスト](https://skeb.jp/search?q=%E3%83%A9%E3%82%B9%E3%83%88) ("last" in katakana), which should actually be イラスト (illustration), except the イ didn't get selected even though it's right there in the commentary, because whatever program they're using only considered the last three characters.
