### ISSUE TITLE
Upload error with AI tags enabled due to suggestions of non-existent tags

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5271]
If autotagger suggests some tag that your instance of Danbooru doesn't have in the database, you get an error `Upload failed: Failed to replace ai_tags because one or more of the new records could not be saved..` on upload because it tries to create ai_tags rows with nil tag_id. The respective tags should be automatically created if they don't already exist. Not sure if it is the cause of #5223.

seems there also might be an issue with ratings. Not sure, but it failed to import the 4th tag in the list which appeared to be rating:s.

**Comment by nottalulah** [comment]
Since this has been open over a year and has a linked PR and was never fixed I'll just assume there is no interest. If anyone else stumbles upon this and cares, here's the code I used in my own instance:

```patch
From b2661fca90cd3f1acefd69327e1a8f27817b3150 Mon Sep 17 00:00:00 2001
From: Talulah <talulah@reunion.is>
Date: Sat, 8 Jul 2023 13:35:44 -0300
Subject: [PATCH] Autotagger: Fix exception when returned tags don't exist.
---
 app/logical/autotagger_client.rb | 9 ++++++++-
 app/logical/media_file.rb        | 4 ++--
 2 files changed, 10 insertions(+), 3 deletions(-)

diff --git a/app/logical/autotagger_client.rb b/app/logical/autotagger_client.rb
index adf64a3a2..a81b413d8 100644
--- a/app/logical/autotagger_client.rb
+++ b/app/logical/autotagger_client.rb
@@ -19,7 +19,14 @@ class AutotaggerClient
     return {} if !response.status.success?
 
     tag_names_with_scores = response.parse.first["tags"]
-    tags = Tag.where(name: tag_names_with_scores.keys).index_by(&:name)
+    tags = Tag.where(name: tag_names_with_scores.keys).pluck(:name, :id).to_h
+
+    missing_tags = tag_names_with_scores.keys - tags.keys
+    if missing_tags.present?
+      ids = Tag.insert_all(missing_tags.map { |tag| { name: tag } }).rows.flatten
+      tags.merge!(missing_tags.zip(ids).to_h)
+    end
+
     tag_names_with_scores.transform_keys(&tags)
   end
 end
diff --git a/app/logical/media_file.rb b/app/logical/media_file.rb
index c48823745..9dd6c8ba6 100644
--- a/app/logical/media_file.rb
+++ b/app/logical/media_file.rb
@@ -244,8 +244,8 @@ class MediaFile
   def ai_tags(autotagger: AutotaggerClient.new)
     tags = autotagger.evaluate(self)
 
-    tags.map do |tag, score|
-      AITag.new(tag: tag, score: (100*score).round)
+    tags.map do |tag_id, score|
+      AITag.new(tag_id: tag_id, score: (100*score).round)
     end
   end
 ```

I don't know if this causes problems with tag caching, but given it will run infrequently I don't think it should be much of an issue.

**Comment by evazion** [comment]
Using `insert_all` is wrong because it doesn't run callbacks. Ignoring callbacks happens to work, but only by accident. We don't need them in this context, but if more callbacks are added in the future it could silently break things.

The only thing we need to skip is name validation, so that we can create rating tags like `rating:g`. That would be better done with `tag.save(validate: false)`. Or by creating them in db/seed.rb, or by using custom validation contexts or magic flags to skip the rule that tags can't be named like `rating:g`, but that's trickier.

On the other hand, if we use `tag.save` or instead of `Tag.insert_all`, we have to be careful about race conditions if multiple people try to create the same missing tags at the same time. That could happen if you open the same upload in multiple tabs, and each one tries to create the same missing tags.

It's also a little unclean to create things in the database when we're just trying to get the AI tags for an image. Doing something like `MediaFile.open('image.jpg').ai_tags` in the console shouldn't the side effect of modifying the database.

Lastly, this still won't create tags with the right category. You'll still be left with a bunch of character and copyright tags marked as gentags. If you actually want to use AI tags in your own instance, you'll probably want to import the list of tag categories somehow. Maybe it would be better to just pre-create all the tags automatically when the site is set up in `db/seed.rb`. Or maybe the AI tagger should just return the category so we can create tags with the right category.

**Comment by nottalulah** [comment]
The main problem is this prevents uploads from finishing at all if you have the autotagger configured, so a few miscategorized character/copyright tags seems better than not being able to upload. I used `insert_all` to avoid creating tags in a loop, which felt wrong, and since tags are a fairly simple type I figured it would be fine. I do think doing it pre-emptively via `db/seed.rb` would be better, but [the tag list from the autotagger repo](https://github.com/danbooru/autotagger/blob/1edfba77c94d77246595d684c501da3abb8b1ccc/data/tags.json) doesn't seem to include categories either so that wouldn't fix the category problem, and this would also require making sure it stays up-to-date if the autotagger model ever changes.
