### ISSUE TITLE
pixiv_ugoira_frame_data alternative

### ISSUE THREAD

**Issue by mikf** [danbooru/danbooru#5294]
I've been using `/posts/ID.json?only=pixiv_ugoira_frame_data` to fetch frame delays for ugoira posts, but https://github.com/danbooru/danbooru/commit/01d10a54f8cd525715d64124a57c88a94becb990 and https://github.com/danbooru/danbooru/commit/c2adf279ee5e66b89f6cff783f82859dc06c25de seem to have removed that functionality.

What other `only` field (or general method) should I use to access ugoira frame delays, now that `pixiv_ugoira_frame_data` was removed? I tried `only=frame_delays`, `media_asset.frame_delays` and many more, but to no avail.

And how can I find these names by myself, if it gets changed again in the future?

**Comment by evazion** [comment]
You can obtain the frame delays like this:

* https://betabooru.donmai.us/posts.json?tags=ugoira&only=id,file_url,media_asset,media_metadata
* https://betabooru.donmai.us/media_metadata.json?search[metadata_has_key]=Ugoira:FrameDelays

Note that this includes only the frame delays, not the filename of each frame like `pixiv_ugoira_frame_data` did. The filenames always have the format `000001.jpg`, `000002.jpg`, etc, so you can generate them yourself.

>And how can I find these names by myself, if it gets changed again in the future?

This stuff isn't documented as well as it could be, but the `available_includes` method in `app/models/post.rb` lists which tables can be used in the `only` field, and `db/structure.sql` lists which fields are available on every table. In this case, frame delays are stored in the `media_metadata.metadata` column, which is a JSON field, which can contain many different types of metadata that aren't specified. Frame delays are shoved in here because it's convenient to think of them as another form of file metadata rather than as a whole separate table.

**Comment by mikf** [comment]
Thank you very much for the quick fix and your comprehensive explanation.
