### ISSUE TITLE
Add fc2 upload support

### ISSUE THREAD

**Issue by nonamethanks** [danbooru/danbooru#5332]
It doesn't get a lot of new uploads nowadays but we have a lot of older posts with those sources which could benefit from fetching the commentary

**Comment by evazion** [comment]
Added support for scraping blog posts, but only when they use the default mobile template:

* http://niyamalog.blog.fc2.com/blog-entry-3.html (works)
* https://killfuckdie.blog.fc2.com/blog-entry-207.html (doesn't work)
* http://oekakigakusyuu.blog97.fc2.com/blog-entry-320.html (doesn't work)

This is probably as good as it gets, because in general FC2 blogs use custom HTML templates that don't have any common structure.
