### ISSUE TITLE
Problem about image upload happened on IOS mobile device

### ISSUE THREAD

**Issue by zk98nanaya** [danbooru/danbooru#5390]
Image upload cannot be accomplished when using IOS mobile device. After pasting the work link or selecting the file on the new upload page, it will show that the "page cannot be opened (translation from another language)".  Only the upload function has this problem on even different IOS devices. And this failure did not occur on PC and Android devices. 

![IMG_3517](https://user-images.githubusercontent.com/121675202/210074230-6074e0b7-3650-4c8a-a008-d3e89c30db99.PNG)

Could you please share if you have any suggestions on this issue? Thank you very much in advance.

**Comment by bipface** [comment]
in discord discussions it was mentioned that simply opening an upload page belonging to the current user (e.g. <https://danbooru.donmai.us/uploads/6657869>) with iOS leads to the error page in the screenshot,

however opening another user's upload (e.g. <https://danbooru.donmai.us/uploads/6654707>) yields the expected 'Access Denied - You do not have permission to visit this page', rather than a browser error page.

**Comment by NamelessContributor** [comment]
English version of the full error message:
> ### Can't open this page
> Try the following tips:
> - Open page in a new Incognito tab
> - Restart Chromium
> - Restart your device

**Comment by evazion** [comment]
Possibly caused by 697691589 but I don't have an iOS device to test it. Does https://danbooru.donmai.us/media_assets/7305924 return the same error?

**Comment by zk98nanaya** [comment]
> Possibly caused by [6976915](https://github.com/danbooru/danbooru/commit/697691589e1472da8f198fbde65080bc6a30f30b) but I don't have an iOS device to test it. Does https://danbooru.donmai.us/media_assets/7305924 return the same error?

Yes, the site page still cannot be opened
