### ISSUE TITLE
Disallow users sending dmails to themselves/DanbooruBot

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5411]
I've seen some people dmailing DanbooruBot trying to reply to the dmails it sends for mentions in comments/forum posts by mistake. I've also seen people dmail themselves trying to reply to someone else. No idea how they accomplished it but it has happened. Given there is little reason to message yourself and no reason to message the bot, I'd suggest disallowing it as it might help prevent confusion/lost replies.

A suggestion was given in Discord to have a flag on the users table for whether a user is capable of receiving dmails or not. That way it would be able to extend to non-DanbooruBot bots, but I don't know if it is worth implementing.

**Comment by HeeroWingZero** [comment]
I'm probably in the minority, but I'd prefer if self-dmails weren't removed. I've used it myself a few times to save post links for unsupported sites when I'm not on my home computer and don't want to log into one of my social media accounts to self-message it, as well as times where I've had to stop in the middle of tagging a humongous image.

**Comment by ErikHumphrey** [comment]
Self-dmails shouldn't be disabled, but if you reply to your own dmail as a follow-up to yourself, it should go to the original recipient rather than yourself. The way they work isn't really treated the same way as email, so it's very easy to dmail yourself.

**Comment by BrokenEagle** [comment]
> I've used it myself a few times to save post links for unsupported sites when I'm not on my home computer and don't want to log into one of my social media accounts to self-message it, as well as times where I've had to stop in the middle of tagging a humongous image.

I'd much rather the user be given a notes text field attribute, which would then allow editing by the user which dmails do not. The Custom CSS user attribute technically could be used for this, but that seems really janky to me. Blacklisted tags and favorited tags could also be used, but in addition to the jank, there could be bugs introduced as well, since neither has a way to comment out portions.

Anyways, since the user is already given at least 1-3 unlimited text fields to play around with, why not give them another which would eliminate the need for self dmails? Just my two red cents.

**Comment by ghost** [comment]
A potential, though more complex, alternative to disallowing it would be to have replies automatically create a comment/forum post in reply, like how sending an email in response to a GitHub issue creates a new comment on it. Though not sure whether that would be desirable behavior.
