### ISSUE TITLE
searching for -pool:any works but pool:none doesn't

### ISSUE THREAD

**Issue by pokeball99** [danbooru/danbooru#5428]
searching for `pool:none` only pulls up one page worth of posts, while `-pool:any` seems to function properly

**Comment by nottalulah** [comment]
Technically paginating works if you manually change the page numbers. The problem is the paginator is told there are 0 posts for pool:none, so it won't generate higher pages.

Culprit seems to be this elsif block

https://github.com/danbooru/danbooru/blob/8813970ed3dc58143c284294e8dd2525c7f2a2a1/app/logical/post_query.rb#L235-L237

It tries to find a pool named "none" which doesn't exist so it defaults to 0 posts. -pool:any doesn't have that issue because -pool makes is_metatag?(:pool) return false.

**Comment by 9suika** [comment]
> there's a similar issue with saved searches, `search:all` gives me one page of results (can be worked around with `&page=n`) but `search:all limit:20` returns 50 pages

**Comment by evazion** [comment]
> there's a similar issue with saved searches, `search:all` gives me one page of results (can be worked around with `&page=n`) but `search:all limit:20` returns 50 pages

Open a separate issue for this. This is a separate problem, I think caused by the fact that `search:all` initially returns zero results and is then updated in the background. The post count of zero gets cached for 5 minutes, which leads to it showing only one page of results.
