### ISSUE TITLE
Uploading large files throws "No space left" error

### ISSUE THREAD

**Issue by decatetsu** [danbooru/danbooru#5432]
I've increased file size limit and video duration using docker-compose.yaml environment configuration as shown below.

![image](https://user-images.githubusercontent.com/56955307/218299820-ef80293e-f830-4d79-bd59-78388145237b.png)

But if I upload 1.3GB file, I catch the next error in my console:

```
danbooru-danbooru-1  | 2023-02-12 08:01:22 +0000 Rack app ("POST /uploads.json" - (172.18.0.1)): #<Errno::ENOSPC: No space left on device @ io_write - /tmp/RackMultipart20230212-78-ssyjgx.mp4>
```

And I have a lot of space, so maybe I misunderstand the error.

On smaller ones (~0.5GB) I had `Upload failed: Request ran for longer than 65000ms`.

**Comment by evazion** [comment]
>danbooru-danbooru-1  | 2023-02-12 08:01:22 +0000 Rack app ("POST /uploads.json" - (172.18.0.1)): #<Errno::ENOSPC: No space left on device @ io_write - /tmp/RackMultipart20230212-78-ssyjgx.mp4>

It looks like Docker Compose mounts `/tmp` as a `tmpfs`, meaning upload temp files are stored in RAM instead of on disk. If an upload is too large you could run out of memory. A workaround is to set `TMPDIR: /var/tmp` in `docker-compose.yaml` so that temp file are stored on disk.

>On smaller ones (~0.5GB) I had Upload failed: Request ran for longer than 65000ms.

By default there's a 65 second request timeout, so file uploads that take longer than this will be canceled. You can increase it by setting the `RACK_REQUEST_TIMEOUT` environment variable to something large like `600` (10 minutes). When you upload a video, we validate that it's playable by playing back the entire video, which might take a long time depending on your hardware and the length of the video.

**Comment by decatetsu** [comment]
Thank you! Everything is fine now.
