### ISSUE TITLE
/artist_urls case-insensitive search is unusably slow

### ISSUE THREAD

**Issue by bipface** [danbooru/danbooru#5445]
Searching `/artist_urls` case-insensitively tends to perform poorly or time-out depending on the method used,

Searches with one or more URLs using `url_lower_space` / `url_lower_array` / `url_lower_comma` all take 10+ seconds or time-out. Adding `limit` sometimes helps but not always:

* https://danbooru.donmai.us/artist_urls?search[url_lower_space]=https%3A%2F%2Ftwitter.com%2FsHiGaTaKe
* https://danbooru.donmai.us/artist_urls?search[url_lower_space]=https%3A%2F%2Ftwitter.com%2FsHiGaTaKe&limit=1
* https://danbooru.donmai.us/artist_urls?search[url_lower_space]=https%3A%2F%2Ftwitter.com%2FsHiGaTaKe%20https%3A%2F%2Ftwitter.com%2Fpuppyypawss
* https://danbooru.donmai.us/artist_urls?search[url_lower_space]=https%3A%2F%2Ftwitter.com%2FsHiGaTaKe%20https%3A%2F%2Ftwitter.com%2Fpuppyypawss&limit=2

These lead to `where_text_includes_lower` which yields sql `lower(url) in (...)` so no surprise about that not hitting the index.

Workarounds I've found which perform faster:

* `url_regex` with a case-insensitive pattern such as <https://danbooru.donmai.us/artist_urls?search[url_regex]=^(https%3A%2F%2Ftwitter%5C.com%2F[sS][hH][iI][gG][aA][tT][aA][kK][eE]|https%3A%2F%2Ftwitter%5C.com%2F[pP][uU][pP][pP][yY][yY][pP][aA][wW][sS][sS])$>. An inconvenient option for clients because they require extra logic for constructing the regex patterns and i'm not sure whether unicode would complicate it.
* `url_matches` with a wildcard which forces use of `where_ilike`, such as <https://danbooru.donmai.us/artist_urls?search[url_matches]=https%3A%2F%2Ftwitter.com%2FsHiGaTaKe*%20https%3A%2F%2Ftwitter.com%2Fpuppyypawss*>. This isn't ideal since it would match prefixes, not just the exact URL, and might not work for URLs which contain a literal space (`%20`) since it splits on spaces. Note that `url_matches` without a wildcard performs a case-sensitive match.

Case-insensitive searching is important for some URLs such as twitter where mixed-case usernames are preserved but treated insensitively ( e.g. the canonical URL <https://twitter.com/PuppyyPawss> is equivalent to <https://twitter.com/puppyypawss> ).

I noticed this issue when running the *translate-pixiv-tags* userscript which performs requests using `search[url_lower_array][]=` to resolve artists. These requests have often been timing-out recently.

**Comment by evazion** [comment]
I made `/artist_urls?search[url_matches]` case-insensitive. User scripts should use this instead of `url_lower_space`.

Adding params like `*_lower_space` was a mistake because they're not usually indexed and because you usually need other normalization beyond just case-insensitivity. For example for URLs there are a variety of ways to write the same URL:

https://betabooru.donmai.us/artist_urls?search[url_matches]=https://twitter.com/ebihurya332
https://betabooru.donmai.us/artist_urls?search[url_matches]=http://twitter.com/ebihurya332
https://betabooru.donmai.us/artist_urls?search[url_matches]=http://twitter.com/ebihurya332/
https://betabooru.donmai.us/artist_urls?search[url_matches]=http://twitter.com/EBIHURYA332
https://betabooru.donmai.us/artist_urls?search[url_matches]=http://mobile.twitter.com/ebihurya332
https://betabooru.donmai.us/artist_urls?search[url_matches]=https://www.pixiv.net/users/11424595
https://betabooru.donmai.us/artist_urls?search[url_matches]=https://www.pixiv.net/en/users/11424595
https://betabooru.donmai.us/artist_urls?search[url_matches]=https://www.pixiv.net/member.php%3Fid=11424595

`url_matches` can handle all of these, `url_lower_space` can't.
