### ISSUE TITLE
Support ActivityPub federation.

### ISSUE THREAD

**Issue by rokejulianlockhart** [danbooru/danbooru#5446]
https://github.com/hummingbird-me/kitsu-server/issues/1316#issue-1582215723 provides my rationale.

**Comment by nonamethanks** [comment]
Do you have an example of posts that would have sources from this site?

**Comment by nottalulah** [comment]
Sorry but that's not much justification for supporting it. It reads more of a "this is popular right now so we should add it" ordeal.

**Comment by rokejulianlockhart** [comment]
@nottalulah and @nonamethanks , I expected that as developers, you would be familiar with the standard and its advantages. I apologize, because that's obviously just subconscious justification for laziness. However, did you visit https://fediverse.party/en/fediverse (per the linked issue)? 

Despite that, I'll summarize:
* Being able to interact with content across sites has allowed me to follow a lot more content creators more closely and via sources that I otherwise would not have, since I can directly aggregate their content via my homeserver. In my case, this is https://mastodon.social/@rokejulianlockhart/following. 
* Because Danbooru contains some brilliant artwork, yet doesn't expose enough features for me to ever bother to use it over something like Pixiv, this would allow me to interact with its content as easily as I do artwork via PixelFed (a federated competitor to Instagram).

Mostly, I hope that the standard's integration would provide some additional traffic due to users being able to access the site's content without having to learn how to use another site nor create an account, thereby (potentially) convincing them that the aforementioned is actually worth the effort. It also helps discovery because users are more easily able to distribute content across networks without just coping the artwork without accreditation. This, to me, is important.

**Comment by nonamethanks** [comment]
Danbooru was designed as a centralized archival hub, so this would require a significant and difficult rewriting of the infrastructure for dubious benefit. 
The main instance would likely never use it due to our high quality requirements that would not be guaranteed on other instances, and if a post meets our quality standards we would want to have it on danbooru anyway, not on adjacent instances, because we're data hoarders.

**Comment by temtemy** [comment]
I'm probably too late to comment on this, but I will give my two cents anyway. I do agree that ActivityPub doesn't make much sense on the uploading side of things. However where I think ActivityPub would make sense is allowing comments on Danbooru images to be done from your fediverse account instead of having to go to Danbooru to post a comment.

I guess possible issues that should be kept in mind if considered is, how would each image be represented in the fediverse, since ActivityPub works by "actors". Would it make sense for each image post be attributed to an "actor account" of the uploader, or the tagged artist? There's also the question of how tags would be represented in the fediverse: should they all be hashtags? But that'd quickly overwhelm the hashtag timelines of microblog instances who federate with Danbooru. Etc...
