### ISSUE TITLE
User tooltips styling broken with user #xxx and @user dtext

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5465]
![image](https://user-images.githubusercontent.com/26291500/224813325-dd6c2ae9-6742-4e98-bd87-0970e9a3c4fe.png)

Dunno if it's related to #5463.

**Comment by nottalulah** [comment]
Closing as dupe. Seems to be caused by this https://github.com/danbooru/danbooru/blob/7b77d08e44eae3b061b2462a54eae030350d2ecb/app/javascript/src/styles/common/dtext.scss#L69-L71

`div.prose li` selector being applied to it. Overriding it with `list-style-type: none` here https://github.com/danbooru/danbooru/blob/7b77d08e44eae3b061b2462a54eae030350d2ecb/app/javascript/src/styles/specific/user_tooltips.scss#L76-L77 will fix it in this case, though the bold problem linked in other issue remains.

**Comment by evazion** [comment]
The root problem is that the tooltip is a child element of the thing that triggers it. This causes CSS rules for the parent element to bleed into the tooltip.

Making the tooltip a child of the `<body>` element rather than the trigger element fixes this, but it breaks other things. As I recall, it breaks nested tooltips where you have a post tooltip and you hover over the uploader name to show the user tooltip. When the post tooltip closes, you want the uploader tooltip to close too, which requires it to be a child of the post tooltip.

The alternative is somehow scoping CSS so that CSS rules for stuff outside the tooltip don't bleed into the tooltip. I don't know how we would do this.

**Comment by evazion** [comment]
This particular case was fixed in 01cef75425609d228b9737e47125e4092aa7a226 where there was also a problem with DText CSS bleeding into embedded ugoiras, but the problem from #5463 remains.
