### ISSUE TITLE
Performance issue with random:x

### ISSUE THREAD

**Issue by nottalulah** [danbooru/danbooru#5471]
Searching for random:x performs at minimum x queries since it generates a random MD5 and selects one post matching it. For random:200 that means at least 200 queries, potentially more if it hits the random_down case. It's supposed to be a faster alternative to order:random, but on large values it ends up significantly slower than order:random.

**Comment by evazion** [comment]
Fixed it to perform a single query using a recursive CTE instead of N queries. It's still doing N searches, but combined into one query so it's faster.

random:N isn't always expected to be faster than order:random. It's faster for large searches or when you only need one or two posts. For small searches (less than 50k posts or so), order:random will probably be faster than random:200.
