### ISSUE TITLE
css/javascript files not loading when using danbooru behind a Kong gateway

### ISSUE THREAD

**Issue by camilovietnam** [danbooru/danbooru#5576]
Hello! 

I am running a Docker container with Kong gateway that is set up to receive requests to `http://localhost/danbooru`, and these have to be redirected to `http://danbooru:3000`, a host which exists in the same docker network

Some links are failing, because they are declared with relative paths. For example, the `/favicon.ico` location, which I believe is declared in here https://github.com/danbooru/danbooru/blob/master/app/views/layouts/default.html.erb#L7

This won't work, because the relative path is telling the browser to search `http://localhost/favicon.ico`, but I need it to search using the canonical URL of danbooru, so it should go to `http://localhost/danbooru/favicon.ico`

I suppose there is no easy way to do this, other than to find all the places where these links are being declared, and prepend `<%= root_url %>` to them?

**Comment by evazion** [comment]
I take it the request is basically to be able to run Danbooru in a subdirectory, so that you get URLs like this:

```
http://localhost/danbooru/posts/1
```

This is now possible with 81921ede. To do it, set `DANBOORU_CANONICAL_URL` in `.env`:

```
DANBOORU_CANONICAL_URL=http://localhost/danbooru
```

This hasn't been thoroughly tested, so there are probably still some random links that aren't relative to the app subdir.

Note that for localhost, a simpler way might be to just use `http://danbooru.localhost` instead of running it in a subdir.
