### ISSUE TITLE
Twitter: `/profile_banners/` links tagged as bad_link

### ISSUE THREAD

**Issue by GHVirus** [danbooru/danbooru#5614]
https://danbooru.donmai.us/posts/6877627

https://pbs.twimg.com/profile_banners/1684767958051229696/1690522090/1500x500

They should not be, because the account’s ID is in the link (after “profile_banners”):

https://twitter.com/i/user/1684767958051229696

**Comment by hdk5** [comment]
https://github.com/danbooru/danbooru/blob/bf3f6ea1c3b55b63828c7c8ed9c16adb9791d3a8/test/unit/sources/twitter_test.rb#L322

**Comment by GHVirus** [comment]
O

**Comment by evazion** [comment]
This is complicated because it violates most of our assumptions about sources.

For sources we assume that:

* An URL is either an image URL, a page URL, or a profile URL.
* Image URLs always belong to a page URL (where a page URL is something like a Twitter or Pixiv post).
* Image URLs never belong to a profile URL (where a profile URL is like a Twitter or Pixiv profile page).
* Page URLs are stable. They return the same image(s) every time.

But banner images violate these assumptions:

* A banner image URL doesn't necessarily have a dedicated page URL. Twitter has these `https://twitter.com/<username>/header_photo` URLs, but not all sites do.
* For sites that don't have a `/header_photo`-type URL, we could use the profile URL instead, but we don't want people putting things like `https://www.pixiv.net/users/1234` as the source of a post because that's nearly always wrong. We assume that profile URLs are never valid sources because they don't normally have images.
* `https://twitter.com/<username>/header_photo` URLs aren't stable. They return a different image every time the artist changes their profile banner, which means they're not good sources because the image they point to can change over time.

Anyway, the fix here is just to special case it so that Twitter profile banners aren't tagged `bad_link`.
