### ISSUE TITLE
Bluesky support

### ISSUE THREAD

**Issue by ZipFile** [danbooru/danbooru#5640]
Post page URL regex: `^https://bsky.app/profile/(.+?)/post/(.+)$` (groups: HANDLE, POST_ID)
Thumbnail URL regex: `^https://cdn.bsky.app/img/.+?/plain/(.+?)/(.+?)@.*$` (groups: DID, CID)
Original Image URL regex: `^https://(?:bsky\.social|.*\.bsky\.network)/xrpc/com\.atproto\.sync\.getBlob\?did=(.*)&cid=(.*)$` (groups: DID, CID)

`DID` from `HANDLE` can be retrieved using [com.atproto.identity.resolveHandle](https://www.docs.bsky.app/docs/api/com-atproto-identity-resolve-handle) API call.

<details>
  <summary>Example:</summary>

  ```sh
  $ curl -L 'https://bsky.social/xrpc/com.atproto.identity.resolveHandle?handle=ixy.bsky.social' | jq .did
  "did:plc:3jogsxcisdcdzwjobhxbav2w"
  ```
</details>

`CID`s from post can be retrieved using [app.bsky.feed.getPostThread](https://www.docs.bsky.app/docs/api/app-bsky-feed-get-post-thread) API call.

<details>
  <summary>Example:</summary>
  
  ```sh
  $ curl -L 'https://bsky.social/xrpc/app.bsky.feed.getPostThread?uri=at://did:plc:3jogsxcisdcdzwjobhxbav2w/app.bsky.feed.post/3kkvo4d4jd32g' -H "Authorization: Bearer $JWT" | jq '.thread.post.record.embed.images[] | {cid: .image.ref."$link", mime: .image.mimeType}'
  {
    "cid": "bafkreiawa4vn5k37h2mlpwuhaqmeog3hsfe3z47iot7reqxjlff6juyge4",
    "mime": "image/jpeg"
  }
  ```
  Note: `$JWT` contains access jwt token. See details below.
</details>

Original image can be retrieved from `DID` and `CID` using [com.atproto.sync.getBlob](https://www.docs.bsky.app/docs/api/com-atproto-sync-get-blob) API call. File extension is not available, but can be deduced from returned mime type, or by using good old `libmagic`.

<details>
  <summary>Example:</summary>

  ```sh
  $ curl -L 'https://bsky.social/xrpc/com.atproto.sync.getBlob?did=did:plc:3jogsxcisdcdzwjobhxbav2w&cid=bafkreiawa4v
n5k37h2mlpwuhaqmeog3hsfe3z47iot7reqxjlff6juyge4' -o image.ext

  $ sha256sum image.ext 
  16072adeab7f3e98b7da870418471b679149bcf3e874ff1242e9594be4d30627  image.ext

  $ file --mime-type image.ext
  image.ext: image/jpeg
  ```
</details>

Auth token can be retrieved using [com.atproto.server.createSession](https://www.docs.bsky.app/docs/api/com-atproto-server-create-session) API call. [com.atproto.server.refreshSession](https://www.docs.bsky.app/docs/api/com-atproto-server-refresh-session
) to refresh expired access tokens.

**Comment by hdk5** [comment]
Additional info:
- user handles can be changed
- for that reason, it may be better to use [app.bsky.actor.getProfile](https://www.docs.bsky.app/docs/api/app-bsky-actor-get-profile) to obtain user data instead, as it accepts both DIDs and handles
- https://bsky.app/profile/did:plc:3jogsxcisdcdzwjobhxbav2w is also a valid secondary profile url
- https://bsky.app/profile/did:plc:3jogsxcisdcdzwjobhxbav2w/post/3kkvo4d4jd32g is a valid post url as well
- for the same reason, it may be better to use post url with user DID instead (for potential `Source::Extractor::Bluesky.page_url`), since otherwise, if the user changes their handle, the url will become `bad_id`

Are you gonna make a PR? Or that's just info for someone else willing to?

**Comment by ZipFile** [comment]
> Are you gonna make a PR?

Unlikely.

> Or that's just info for someone else willing to?

This.
