### ISSUE TITLE
Error response from daemon: pull access denied for danbooru, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by cirnoscodingclass** [danbooru/danbooru#5659]
Made many edits to the repos files and trying to now trying to see it run in production running `sudo DANBOORU_IMAGE=danbooru docker compose up` , but I keep encountering the error:
```
[+] Running 4/4
 ✘ jobs Error                                                                                                                                                                                              0.5s 
 ✘ nginx Error                                                                                                                                                                                             0.5s 
 ✘ danbooru Error                                                                                                                                                                                          0.5s 
 ✘ cron Error                                                                                                                                                                                              0.5s 
Error response from daemon: pull access denied for danbooru, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

edit: Made an account as suggested by the error, but no change in behavior.

**Comment by cirnoscodingclass** [comment]
Issue was the host machine running out of memory during `bin/build-docker-image` and never completed. Running `git archive HEAD | docker buildx build - --target production  --tag danbooru --file Dockerfile --load` helped to complete the build but may require multiple restarts if the build does not cache the image and its still running out of memory.

**Comment by evazion** [comment]
It's possible to use [docker image save](https://docs.docker.com/reference/cli/docker/image/save/) and [docker image load](https://docs.docker.com/reference/cli/docker/image/load/) to build the image on one machine and transfer it to another. Or use [docker push](https://docs.docker.com/reference/cli/docker/image/push/), but that requires making an account at a Docker registry.

The problem is that Docker builds each image stage in parallel by default, and that can consume a lot of memory when it starts building things like FFmpeg, Ruby, libvips, etc all at the same time. It's possible to limit the parallelism with [max-parallelism](https://docs.docker.com/build/buildkit/configure/#max-parallelism), but it requires making a config file and using `docker buildx create` to make Docker use it.
