### ISSUE TITLE
Add bookmarklet support for Carrd

### ISSUE THREAD

**Issue by HeeroWingZero** [danbooru/danbooru#5713]
While it's typically used simply to list all of an artist's sites, Carrd also allows users to build simple portfolio websites.

Example site:
https://caminukai-art.carrd.co/

Example post:
https://caminukai-art.carrd.co/#fanart-shadowheartguidance

Example thumbnail:
https://caminukai-art.carrd.co/assets/images/gallery12/63efd18f.jpg?v=3850522b

Example direct:
https://caminukai-art.carrd.co/assets/images/gallery21/a86d9fc4.jpg?v=3850522b (the ?v= part at the end can be deleted and the image still loads exactly the same)

There are also portfolio pages that feature multiple images, but no individual pages for each image see below:
https://lytell.carrd.co/#portfolio - each image can be clicked to zoom, but no separate URL for each one.
https://badkrol.carrd.co/#commission - images mixed with text, images cannot be clicked on

Carrd also supports videos, see the following example:
https://rosymiz.carrd.co/

The direct link for a video looks like this:
https://rosymiz.carrd.co/assets/videos/video02.mp4?v=c6f079b5

**Comment by evazion** [comment]
This is tricky because Carrd is a custom website builder, so each site is different. There's not much common structure between different websites. This tries to do the best it can in getting the commentary, but sometimes it's hard to separate the main content of the page from the header, footer, or sidebar. And sometimes there are sites like https://jun-portfolio.carrd.co where the main content is shoved into the footer.

Carrd also supports custom domain names. These aren't supported because I don't know of any to test.

Lastly, some sites have background images or videos (ex: `post #7429019` / https://silvivtuber.carrd.co) which we don't extract because they're part of every page.
